/*
 * $Id$
 */

/*
 *   fun_name            fun_string     ieee_compatible
 */

WLP (WLCOMP_All, "All", TRUE)
WLP (WLCOMP_Cubes, "Cubes", FALSE)
WLP (WLCOMP_ConstSegs, "ConstSegs", FALSE)
WLP (WLCOMP_NoBlocking, "NoBlocking", TRUE)
WLP (WLCOMP_BvL0, "BvL0", FALSE)
WLP (WLCOMP_BvL1, "BvL1", FALSE)
WLP (WLCOMP_BvL2, "BvL2", FALSE)
WLP (WLCOMP_Ubv, "Ubv", FALSE)
WLP (WLCOMP_Scheduling, "Scheduling", TRUE)
WLP (WLCOMP_Tasksel, "Tasksel", TRUE)
