/*
 * File defines some dummy functions that are normally generated by sac2c
 * We need this in order to test the runtime libraries directly.
 */

#include <stddef.h>

void *SACARGcopyDataUdt (int type, int size, void *data) { return NULL; }
