<?xml version="1.0"?>
<!--
  $Log$
  Revision 1.1  2004/07/03 15:14:59  sah
  Initial revision

-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
version="1.0">

<xsl:output method="text" indent="no"/>
<xsl:strip-space elements="*"/>

<!-- This stylesheet generates a node_basic.h file defining all the macros
     to the different attributes and the MakeXXX functions for nodes       -->

<xsl:template match="/">
  <xsl:text>
/*****************************************************************************
 * node_basic.h generated by ast2node_basic_h.xsl                            *
 *                                                                           *
 * DO NOT EDIT THIS FILE, EDIT ast.xml INSTEAD!                              *
 *****************************************************************************/

#ifndef _NODE_BASIC_H
#define _NODE_BASIC_H

#include "tree_basic.h"
#include "types.h"
#include "new_types.h"
#include "DataFlowMask.h"
#include "globals.h"

  </xsl:text>
  <xsl:apply-templates select="//syntaxtree/node"/>
  <xsl:text>

#endif
  </xsl:text>
</xsl:template>

<xsl:template match="node">
  <xsl:text>

/*****************************************************************************
 * macros and functions for N_</xsl:text><xsl:value-of select="@name"/><xsl:text>
 *****************************************************************************/

  </xsl:text>
  <xsl:apply-templates select="sons/son" mode="accessors"/>
  <xsl:apply-templates select="attributes/attribute" mode="accessors"/>
  <xsl:apply-templates select="." mode="make"/>
</xsl:template>

<!-- generate accessors for nodes -->
<xsl:template match="son" mode="accessors">
  <xsl:value-of select="'#define '"/>
  <xsl:call-template name="uppercase">
    <xsl:with-param name="string"><xsl:value-of select="../../@name"/></xsl:with-param>
  </xsl:call-template>
  <xsl:value-of select="'_'"/>
  <xsl:call-template name="uppercase">                                          
    <xsl:with-param name="string"><xsl:value-of select="@name"/></xsl:with-param>
  </xsl:call-template>
  <xsl:value-of select="'(n) n->node['"/>
  <xsl:value-of select="position() - 1"/>
  <xsl:value-of select="']'"/>
  <xsl:call-template name="newline"/>
</xsl:template>

<!-- generate accessors for attributes -->
<xsl:template match="attribute" mode="accessors">
  <xsl:value-of select="'#define '"/>
  <xsl:call-template name="uppercase">
    <xsl:with-param name="string"><xsl:value-of select="../../@name"/></xsl:with-param>
  </xsl:call-template>
  <xsl:value-of select="'_'"/>
  <xsl:call-template name="uppercase">
    <xsl:with-param name="string"><xsl:value-of select="@name"/></xsl:with-param>
  </xsl:call-template>
  <xsl:value-of select="'(n'" />
  <!-- if the attribute is an array, we need to add the index to the macro -->
  <xsl:if test="//attributetypes/type[@name = current()/type/@name]/@size" >
    <xsl:value-of select="', x'" />
  </xsl:if>
  <xsl:value-of select="') n->attribs.N_'"/> 
  <xsl:value-of select="../../@name"/>
  <xsl:value-of select="'.'"/>
  <xsl:value-of select="@name"/>
  <!-- if the attribute is an array, we need to add the index to the macro -->
  <xsl:if test="//attributetypes/type[@name = current()/type/@name]/@size" >
    <xsl:value-of select="'[x]'" />
  </xsl:if>
  <xsl:call-template name="newline"/>
</xsl:template>

<!-- generate a make function -->
<xsl:template match="node" mode="make">
  <xsl:value-of select="'extern node *Make'"/>
  <xsl:value-of select="@name"/>
  <xsl:value-of select="'( '"/>
  <!-- permanent attributes first -->
  <xsl:apply-templates select="attributes/attribute[phases/all]" mode="make"/>
  <!-- add a , if needed -->
  <xsl:if test="attributes/attribute[phases/all]">
    <xsl:if test="sons/son">
      <xsl:value-of select="' ,'"/>
    </xsl:if>
  </xsl:if>
  <!-- sons are last parameters -->
  <xsl:apply-templates select="sons/son" mode="make"/>
  <xsl:value-of select="');'"/>
</xsl:template>

<xsl:template match="son" mode="make">
  <xsl:if test="position() != 1">
    <xsl:value-of select="' ,'"/>
  </xsl:if>
  <xsl:value-of select="'node * '"/>
  <xsl:value-of select="@name"/>
</xsl:template>

<xsl:template match="attribute" mode="make">
  <xsl:if test="position() != 1">
    <xsl:value-of select="' ,'"/>   
  </xsl:if>
  <xsl:value-of select="//attributetypes/type[@name = current()/type/@name]/@ctype"/>
  <!-- if it is an array, we have to add an indirection -->
  <xsl:if test="//attributetypes/type[@name = current()/type/@name]/@size">
    <xsl:value-of select="'*'" />
  </xsl:if>
  <xsl:value-of select="' '"/>
  <xsl:value-of select="@name"/>
</xsl:template>

<!-- basic function for uppercase -->
<xsl:template name="uppercase">
  <xsl:param name="string"/>
  <xsl:value-of select="translate($string, 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')"/>
</xsl:template>

<!-- basic function for newlines -->
<xsl:template name="newline">
  <xsl:text>
  </xsl:text>
</xsl:template>
</xsl:stylesheet>


