#
# $Log$
# Revision 1.1  2001/11/14 13:02:58  sbs
# Initial revision
#
#



################################################################################
#
# C compiler setup:
#
# legal values for CC and CCPROD currently are:
#    gcc
#    cc
#
CC           := gcc
CCPROD       := gcc

#
# gcc specific flags:
#
gcc_FLAGS      := -ansi -Wall -g
gcc_PROD_FLAGS := -ansi -Wall -g -O3

#
# cc specific flags:
#
cc_FLAGS      := -erroff=E_CAST_DOESNT_YIELD_LVALUE -g
cc_PROD_FLAGS := -erroff=E_CAST_DOESNT_YIELD_LVALUE -g -xO4

################################################################################
#
# OS setup:
#
# legal values for OS currently are:
#    SOLARIS_SPARC
#    LINUX_X86
#    OSF_ALPHA
#    OSX_MAC
#
# to allow easy changes: 
# do not delete os lines, but "comment" all not used lines
#
OS        := SOLARIS_SPARC
#OS        := LINUX_X86
#OS        := OSF_ALPHA
#OS        := OSX_MAC

#
# SOLARIS_SPARC specific flags and libraries:
#
#
# The switch __EXTENSIONS__ must be set under Solaris in order to avoid warnings
# when using non-ANSI-compliant functions.
# Currently, these are popen(), pclose(), tempnam(), and strdup().
#
SOLARIS_SPARC_FLAGS := -D__EXTENSIONS__ -D__STDC__=0
SOLARIS_SPARC_LIBS  := -ll

#
# LINUX_X86 specific flags and libraries:
#
LINUX_X86_FLAGS     := -D_POSIX_SOURCE -D_SVID_SOURCE -D_BSD_SOURCE
LINUX_X86_LIBS      := -lfl

#
# OSF_ALPHA specific flags and libraries:
#
OSF_ALPHA_FLAGS    := -D_OSF_SOURCE 
OSF_ALPHA_LIBS     := -ll

#
# OSX_MAC specific flags and libraries:
#
OSX_MAC_FLAGS    := 
OSX_MAC_LIBS     := -ll

################################################################################
#
# general setup:
#

CCFLAGS      := $($(CC)_FLAGS) $($(OS)_FLAGS)
CCPROD_FLAGS := $($(CCPROD)_PROD_FLAGS) $($(OS)_FLAGS) 

CFLAGS       := -DSHOW_MALLOC -DSAC_FOR_$(OS)
CPROD_FLAGS  := -DDBUG_OFF -DPRODUCTION -DSAC_FOR_$(OS)

MAKE_NORM    := $(MAKE) CC="$(CC)" CCFLAGS="$(CCFLAGS)" CFLAGS="$(CFLAGS)" OS="$(OS)"
MAKE_PROD    := $(MAKE) CC="$(CCPROD)" CCFLAGS="$(CCPROD_FLAGS)" CFLAGS="$(CPROD_FLAGS)" OS="$(OS)"
MAKEFLAGS    += --no-print-directory

TAR          :=tar
LIBS         :=-lm $($(OS)_LIBS)
EFLIBS       :=-L/home/sacbase/efence -lefence
RM           :=rm -f
GZIP         :=gzip -f
ECHO         :=echo

ifeq ($(OS),OSF_ALPHA)
  LEX     := flex -n
  YACC    := yacc -dv
else
  LEX     := flex -n
  YACC    := bison -y -dv
endif

ifeq ($(OS),SOLARIS_SPARC)
  YYFLAGS   := -DYYDEBUG
else
  YYFLAGS   :=
endif



