/* $Id$ */

/** <!--********************************************************************-->
 *
 * @defgroup cwh Create wrapper header
 *
 * Creates a wrapper header file from a given syntax tree.
 *
 * @ingroup cwh
 *
 * @{
 *
 *****************************************************************************/

/** <!--********************************************************************-->
 *
 * @file creater_wrapper_header.c
 *
 * Prefix: CWH
 *
 *****************************************************************************/
#include "create_wrapper_header.h"

/*
 * Other includes go here
 */
#include "dbug.h"
#include "traverse.h"
#include "tree_basic.h"
#include "memory.h"
#include "filemgr.h"
#include "globals.h"
#include "build.h"
#include "stringset.h"
#include "str_buffer.h"
#include "namespaces.h"
#include "str.h"

/** <!--********************************************************************-->
 *
 * @name INFO structure
 * @{
 *
 *****************************************************************************/
struct INFO {
    bool inbundle;
    FILE *file;
    int counter;
};

/**
 * A template entry in the template info structure
 */
#define INFO_INBUNDLE(n) ((n)->inbundle)
#define INFO_FILE(n) ((n)->file)
#define INFO_COUNTER(n) ((n)->counter)

static info *
MakeInfo ()
{
    info *result;

    DBUG_ENTER ("MakeInfo");

    result = MEMmalloc (sizeof (info));

    INFO_INBUNDLE (result) = FALSE;
    INFO_FILE (result) = NULL;
    INFO_COUNTER (result) = 0;

    DBUG_RETURN (result);
}

static info *
FreeInfo (info *info)
{
    DBUG_ENTER ("FreeInfo");

    info = MEMfree (info);

    DBUG_RETURN (info);
}
/** <!--********************************************************************-->
 * @}  <!-- INFO structure -->
 *****************************************************************************/

/** <!--********************************************************************-->
 *
 * @name Entry functions
 * @{
 *
 *****************************************************************************/
/** <!--********************************************************************-->
 *
 * @fn node *CWHdoCreateWrapperHeader( node *syntax_tree)
 *
 *****************************************************************************/
node *
CWHdoCreateWrapperHeader (node *syntax_tree)
{
    info *info;

    DBUG_ENTER ("CWHdoCreateWrapperHeader");

    info = MakeInfo ();

    TRAVpush (TR_cwh);
    syntax_tree = TRAVdo (syntax_tree, info);
    TRAVpop ();

    info = FreeInfo (info);

    DBUG_RETURN (syntax_tree);
}

/** <!--********************************************************************-->
 * @}  <!-- Entry functions -->
 *****************************************************************************/

/** <!--********************************************************************-->
 *
 * @name Static helper funcions
 * @{
 *
 *****************************************************************************/

/** <!-- ****************************************************************** -->
 * @fn str_buf *PrintModuleNames( const char *module, strstype_t kind,
 *                                str_buf *buffer)
 *
 * @brief strsfoldfun that appends a module name with prepended C
 *        comment * to a string buffer.
 *
 * @param module name of module
 * @param kind   ignored
 * @param buffer buffer to print to
 *
 * @return the extended string buffer
 ******************************************************************************/
static str_buf *
PrintModuleNames (const char *module, strstype_t kind, str_buf *buffer)
{
    DBUG_ENTER ("PrintModuleNames");

    buffer = SBUFprintf (buffer, " *   %s\n", module);

    DBUG_RETURN (buffer);
}

/** <!--********************************************************************-->
 *
 * @fn void PrintFileHeader(FILE *file);
 *
 * @brief Prints the header for the include file to be generated.
 *
 *****************************************************************************/
static void
PrintFileHeader (FILE *file)
{
    str_buf *buffer;
    char *modules;

    DBUG_ENTER ("PrintFileHeader");

    buffer = SBUFcreate (100);
    buffer = STRSfold ((strsfoldfun_p)PrintModuleNames, global.exported_modules, buffer);
    modules = SBUF2str (buffer);
    buffer = SBUFfree (buffer);

    fprintf (file,
             "/*\n"
             " * C interface header file for modules:\n"
             " *\n"
             "%s"
             " *\n"
             " * generated by sac4c %s (%s) rev %s\n"
             " */\n\n"
             "#include \"sac4c.h\"\n\n",
             modules, global.version_id, build_style, build_rev);

    DBUG_VOID_RETURN;
}

/** <!--********************************************************************-->
 * @}  <!-- Static helper functions -->
 *****************************************************************************/

/** <!--********************************************************************-->
 *
 * @name Traversal functions
 * @{
 *
 *****************************************************************************/

/** <!--********************************************************************-->
 *
 * @fn node *CWHfunbundle(node *arg_node, info *arg_info)
 *
 * @brief
 *
 *****************************************************************************/
node *
CWHfunbundle (node *arg_node, info *arg_info)
{
    char *safename, *safens;

    DBUG_ENTER ("CWHfunbundle");

    INFO_INBUNDLE (arg_info) = TRUE;

    DBUG_ASSERT ((FUNBUNDLE_FUNDEF (arg_node) != NULL), "empty funbundle found!");

    safename = STRreplaceSpecialCharacters (FUNBUNDLE_NAME (arg_node));
    safens = STRreplaceSpecialCharacters (NSgetName (FUNBUNDLE_NS (arg_node)));

    fprintf (INFO_FILE (arg_info), "SAC4C_EXTERN SAC4C_FUNNAME( %d, %s, %s) ( ",
             FUNBUNDLE_ARITY (arg_node), safens, safename);

    safens = MEMfree (safens);
    safename = MEMfree (safename);

    FUNBUNDLE_FUNDEF (arg_node) = TRAVdo (FUNBUNDLE_FUNDEF (arg_node), arg_info);

    fprintf (INFO_FILE (arg_info), ");\n\n");

    INFO_INBUNDLE (arg_info) = FALSE;

    if (FUNBUNDLE_NEXT (arg_node) != NULL) {
        FUNBUNDLE_NEXT (arg_node) = TRAVdo (FUNBUNDLE_NEXT (arg_node), arg_info);
    }

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *CWHfundef(node *arg_node, info *arg_info)
 *
 * @brief
 *
 *****************************************************************************/
node *
CWHfundef (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("CWHfundef");

    if (INFO_INBUNDLE (arg_info)) {
        if (FUNDEF_RETS (arg_node) != NULL) {
            FUNDEF_RETS (arg_node) = TRAVdo (FUNDEF_RETS (arg_node), arg_info);
            fprintf (INFO_FILE (arg_info), ", ");
        }

        if (FUNDEF_ARGS (arg_node) != NULL) {
            FUNDEF_ARGS (arg_node) = TRAVdo (FUNDEF_ARGS (arg_node), arg_info);
        } else {
            fprintf (INFO_FILE (arg_info), "SAC4C_VOID");
        }
    } else if (FUNDEF_NEXT (arg_node) != NULL) {
        FUNDEF_NEXT (arg_node) = TRAVdo (FUNDEF_NEXT (arg_node), arg_info);
    }

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *CWHarg(node *arg_node, info *arg_info)
 *
 * @brief
 *
 *****************************************************************************/
node *
CWHarg (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("CWHarg");

    INFO_COUNTER (arg_info)++;

    fprintf (INFO_FILE (arg_info), "SAC4C_ARG( %d)", INFO_COUNTER (arg_info));

    if (ARG_NEXT (arg_node) != NULL) {
        fprintf (INFO_FILE (arg_info), ", ");
        ARG_NEXT (arg_node) = TRAVdo (ARG_NEXT (arg_node), arg_info);
    }

    INFO_COUNTER (arg_info)--;

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *CWHret(node *arg_node, info *arg_info)
 *
 * @brief
 *
 *****************************************************************************/
node *
CWHret (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("CWHfundef");

    INFO_COUNTER (arg_info)++;

    fprintf (INFO_FILE (arg_info), "SAC4C_RET( %d)", INFO_COUNTER (arg_info));

    if (RET_NEXT (arg_node) != NULL) {
        fprintf (INFO_FILE (arg_info), ", ");
        RET_NEXT (arg_node) = TRAVdo (RET_NEXT (arg_node), arg_info);
    }

    INFO_COUNTER (arg_info)--;

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *CWHmodule(node *arg_node, info *arg_info)
 *
 * @brief
 *
 *****************************************************************************/
node *
CWHmodule (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("CWHmodule");

    INFO_FILE (arg_info) = FMGRwriteOpen ("%s.h", global.outfilename);

    PrintFileHeader (INFO_FILE (arg_info));

    if (MODULE_FUNS (arg_node) != NULL) {
        MODULE_FUNS (arg_node) = TRAVdo (MODULE_FUNS (arg_node), arg_info);
    }

    INFO_FILE (arg_info) = FMGRclose (INFO_FILE (arg_info));

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 * @}  <!-- Traversal functions -->
 *****************************************************************************/

/** <!--********************************************************************-->
 * @}  <!-- Create Wrapper Headers -->
 *****************************************************************************/
