#!/bin/sh

while [ $# -gt 0 ]
do
  case $1 in
      -I*) include="${include} $1"
          ;;
      -o*) output=$2; shift
          ;;
      -c*) arg_c="-c"
          ;;
      -*)
          ;;
      *) infile="${infile} $1"
          ;;
  esac
  shift
done

gcc ${include} ${arg_c} -E -P -o ${output}.sl ${infile}

slc -o ${output} ${output}.sl
