#!/bin/sh

# This script provides an interface to the slc compiler

# Do not change bin/comslc change
# src/tools/comslc/comslc

backend=`echo $1|sed -e s/sl_//`
shift

while [ $# -gt 0 ]
do
  case $1 in
      -I*) include="${include} $1"
          ;;
      -o*) output=$2; shift
          ;;
      -c*) arg_c="-c"
          ;;
      -lsac_seq)
          ;;
      -l*) libs="${libs} $1"
          ;;
      -L*) libs="${libs} $1"
          ;;
      -g) arg_g="-g"
          ;;
      -*)
          ;;
      *) infile="${infile} $1"
          ;;
  esac
  shift
done

if [ "$output" == "" ]
then
    output=`basename $infile .c`
fi

#gcc ${include} -E -P -o ${output}.sl ${infile}

slc -b ${backend} ${include} ${arg_c} -o ${output} ${infile} ${libs} ${arg_g}
