
#ifndef _sac_check_h
#define _sac_check_h

extern node *CHKCheck (node *arg_node);

extern node *CHKannotate (node *arg_node, info *arg_info);
extern node *CHKap (node *arg_node, info *arg_info);
extern node *CHKarg (node *arg_node, info *arg_info);
extern node *CHKarray (node *arg_node, info *arg_info);
extern node *CHKassign (node *arg_node, info *arg_info);
extern node *CHKavis (node *arg_node, info *arg_info);
extern node *CHKblock (node *arg_node, info *arg_info);
extern node *CHKbool (node *arg_node, info *arg_info);
extern node *CHKcast (node *arg_node, info *arg_info);
extern node *CHKchar (node *arg_node, info *arg_info);
extern node *CHKcond (node *arg_node, info *arg_info);
extern node *CHKcseinfo (node *arg_node, info *arg_info);
extern node *CHKcwrapper (node *arg_node, info *arg_info);
extern node *CHKdataflowgraph (node *arg_node, info *arg_info);
extern node *CHKdataflownode (node *arg_node, info *arg_info);
extern node *CHKdo (node *arg_node, info *arg_info);
extern node *CHKdot (node *arg_node, info *arg_info);
extern node *CHKdouble (node *arg_node, info *arg_info);
extern node *CHKempty (node *arg_node, info *arg_info);
extern node *CHKex (node *arg_node, info *arg_info);
extern node *CHKexport (node *arg_node, info *arg_info);
extern node *CHKexprs (node *arg_node, info *arg_info);
extern node *CHKfloat (node *arg_node, info *arg_info);
extern node *CHKfuncond (node *arg_node, info *arg_info);
extern node *CHKfundef (node *arg_node, info *arg_info);
extern node *CHKicm (node *arg_node, info *arg_info);
extern node *CHKid (node *arg_node, info *arg_info);
extern node *CHKimport (node *arg_node, info *arg_info);
extern node *CHKlet (node *arg_node, info *arg_info);
extern node *CHKmodul (node *arg_node, info *arg_info);
extern node *CHKmop (node *arg_node, info *arg_info);
extern node *CHKmt (node *arg_node, info *arg_info);
extern node *CHKmtalloc (node *arg_node, info *arg_info);
extern node *CHKmtsignal (node *arg_node, info *arg_info);
extern node *CHKmtsync (node *arg_node, info *arg_info);
extern node *CHKncode (node *arg_node, info *arg_info);
extern node *CHKngenerator (node *arg_node, info *arg_info);
extern node *CHKnpart (node *arg_node, info *arg_info);
extern node *CHKnum (node *arg_node, info *arg_info);
extern node *CHKnwith (node *arg_node, info *arg_info);
extern node *CHKnwith2 (node *arg_node, info *arg_info);
extern node *CHKnwithid (node *arg_node, info *arg_info);
extern node *CHKnwithop (node *arg_node, info *arg_info);
extern node *CHKobjdef (node *arg_node, info *arg_info);
extern node *CHKok (node *arg_node, info *arg_info);
extern node *CHKpragma (node *arg_node, info *arg_info);
extern node *CHKprf (node *arg_node, info *arg_info);
extern node *CHKprovide (node *arg_node, info *arg_info);
extern node *CHKreturn (node *arg_node, info *arg_info);
extern node *CHKsetwl (node *arg_node, info *arg_info);
extern node *CHKspmd (node *arg_node, info *arg_info);
extern node *CHKssacnt (node *arg_node, info *arg_info);
extern node *CHKssastack (node *arg_node, info *arg_info);
extern node *CHKst (node *arg_node, info *arg_info);
extern node *CHKstop (node *arg_node, info *arg_info);
extern node *CHKstr (node *arg_node, info *arg_info);
extern node *CHKsymbol (node *arg_node, info *arg_info);
extern node *CHKsync (node *arg_node, info *arg_info);
extern node *CHKtcfuninfo (node *arg_node, info *arg_info);
extern node *CHKtypedef (node *arg_node, info *arg_info);
extern node *CHKuse (node *arg_node, info *arg_info);
extern node *CHKvardec (node *arg_node, info *arg_info);
extern node *CHKvinfo (node *arg_node, info *arg_info);
extern node *CHKwhile (node *arg_node, info *arg_info);
extern node *CHKwlblock (node *arg_node, info *arg_info);
extern node *CHKwlgrid (node *arg_node, info *arg_info);
extern node *CHKwlgridvar (node *arg_node, info *arg_info);
extern node *CHKwlseg (node *arg_node, info *arg_info);
extern node *CHKwlsegvar (node *arg_node, info *arg_info);
extern node *CHKwlstride (node *arg_node, info *arg_info);
extern node *CHKwlstridevar (node *arg_node, info *arg_info);
extern node *CHKwlublock (node *arg_node, info *arg_info);

#endif /*_sac_check_h */
