/*
 * $Log$
 * Revision 1.23  2004/11/17 19:49:46  sah
 * added visibility support
 *
 * Revision 1.22  2004/11/14 15:24:47  sah
 * some cleanup
 *
 * Revision 1.21  2004/11/07 18:09:55  sah
 * changes due to new signature of stringset.h
 *
 * Revision 1.20  2004/11/04 14:53:43  sah
 * implemented dependencies between modules
 *
 * Revision 1.19  2004/11/03 17:22:21  sah
 * typedefs and objdefs are serialized now as well
 *
 * Revision 1.18  2004/11/02 14:59:01  sah
 * extended serialize traversal
 *
 * Revision 1.17  2004/11/01 21:56:26  sah
 * added a missing newline and some
 * further support for debugging
 *
 * Revision 1.16  2004/10/28 17:23:40  sah
 * added serialisation of dependency tables
 *
 * Revision 1.15  2004/10/26 09:35:55  sah
 * added serialization of links
 *
 * Revision 1.14  2004/10/25 11:58:47  sah
 * major code cleanup
 *
 * Revision 1.13  2004/10/22 15:24:29  sah
 * added STE_wrapperxxx
 *
 * Revision 1.12  2004/10/17 17:03:20  sah
 * now the generated code no more contains
 * any sac2c specific types or enums (hopefully)
 *
 * Revision 1.11  2004/10/15 10:19:26  sah
 * fixed typo.
 *
 * Revision 1.10  2004/10/15 10:03:58  sah
 * removed old module system nodes in
 * new ast mode
 *
 * Revision 1.9  2004/10/11 16:56:07  sah
 * added SerializeBuildStack
 *
 * Revision 1.8  2004/10/01 08:13:10  sah
 * fixed include to avoid warning
 * on linux platform
 *
 * Revision 1.7  2004/09/30 20:15:52  sah
 * removed some compiler warnings
 *
 * Revision 1.6  2004/09/27 13:18:12  sah
 * implemented new serialization scheme
 *
 * Revision 1.5  2004/09/24 20:21:53  sah
 * intermediate version
 *
 * Revision 1.4  2004/09/23 21:12:25  sah
 * ongoing implementation
 *
 * Revision 1.3  2004/09/21 16:34:27  sah
 * ongoing implementation of
 * serialize traversal
 *
 * Revision 1.2  2004/09/21 09:49:34  sah
 * fixed missing ;
 *
 * Revision 1.1  2004/09/20 19:55:13  sah
 * Initial revision
 *
 *
 *
 */

#define NEW_INFO

#include "tree_basic.h"
#include "filemgr.h"
#include "stdio.h"
#include "serialize_info.h"
#include "serialize_stack.h"
#include "traverse.h"
#include "symboltable.h"
#include "precompile.h"
#include "convert.h"
#include "stringset.h"
#include <string.h>

#define MAX_FUN_NAME_LEN 255

/*
 * INFO functions
 */

static info *
MakeInfo ()
{
    info *result;

    DBUG_ENTER ("MakeInfo");

    result = Malloc (sizeof (info));

    INFO_SER_FILE (result) = NULL;
    INFO_SER_STACK (result) = NULL;
    INFO_SER_TABLE (result) = STInit ();
    INFO_SER_AST (result) = NULL;

    DBUG_RETURN (result);
}

static info *
FreeInfo (info *info)
{
    DBUG_ENTER ("FreeInfo");

    INFO_SER_TABLE (info) = STDestroy (INFO_SER_TABLE (info));

    info = Free (info);

    DBUG_RETURN (info);
}

serstack_t *
SerializeBuildSerStack (node *arg_node)
{
    info *info;
    funtab *store_tab;
    serstack_t *stack;

    DBUG_ENTER ("SerializeBuildSerStack");

    info = MakeInfo ();
    stack = SerStackInit ();

    INFO_SER_STACK (info) = stack;

    store_tab = act_tab;
    act_tab = sbt_tab;

    arg_node = Trav (arg_node, info);

    act_tab = store_tab;

    info = FreeInfo (info);

    DBUG_EXECUTE ("BST", SerStackDump (stack););

    DBUG_RETURN (stack);
}

static node *
StartSerializeTraversal (node *node, info *info)
{
    funtab *store_tab;

    DBUG_ENTER ("StartSerializeTraversal");

    store_tab = act_tab;
    act_tab = set_tab;

    node = Trav (node, info);

    act_tab = store_tab;

    DBUG_RETURN (node);
}

static node *
StartSerializeLinkTraversal (node *node, info *info)
{
    funtab *store_tab;

    DBUG_ENTER ("StartSerializeLinkTraversal");

    store_tab = act_tab;
    act_tab = sel_tab;

    node = Trav (node, info);

    act_tab = store_tab;

    DBUG_RETURN (node);
}

static void
GenerateSerFileHead (FILE *file)
{
    DBUG_ENTER ("GenerateSerFileHead");

    fprintf (file, "/* generated by sac2c %s */\n\n", version_id);
    fprintf (file, "#include \"sac_serialize.h\"\n\n");

    fprintf (file, "#define DROP( x, y) y\n");
    fprintf (file, "#define NULL (void *) 0\n");

    DBUG_VOID_RETURN;
}

static void
GenerateSerSymbolTableAdd (STsymbol_t *symbol, STentry_t *entry, FILE *file)
{
    DBUG_ENTER ("GenerateSerSymbolTableAdd");

    fprintf (file, "STAdd( \"%s\", %d, \"%s\", %d, result);\n", STSymbolName (symbol),
             STSymbolVisibility (symbol), STEntryName (entry), STEntryType (entry));

    DBUG_VOID_RETURN;
}

static void
GenerateSerSymbolTableHead (node *module, FILE *file)
{
    DBUG_ENTER ("GenerateSerSymbolTableHead");

    fprintf (file, "void *__%s__SYMTAB()\n", MODUL_NAME (module));

    fprintf (file, "{\nvoid *result;\n");
    fprintf (file, "result = STInit();\n");

    DBUG_VOID_RETURN;
}

static void
GenerateSerSymbolTableTail (node *module, FILE *file)
{
    DBUG_ENTER ("GenerateSerSymbolTableTail");

    fprintf (file, "return( result);\n");
    fprintf (file, "}\n");

    DBUG_VOID_RETURN;
}

static void
SerializeSymbolTableSymbol (STsymbol_t *symbol, STtable_t *table, FILE *file)
{
    STentryiterator_t *iterator;

    DBUG_ENTER ("SerializeSymbolTableSymbol");

    iterator = STEntryIteratorGet (STSymbolName (symbol), table);

    while (STEntryIteratorHasMore (iterator)) {
        GenerateSerSymbolTableAdd (symbol, STEntryIteratorNext (iterator), file);
    }

    iterator = STEntryIteratorRelease (iterator);

    DBUG_VOID_RETURN;
}

static void
SerializeSymbolTable (node *module, STtable_t *table)
{
    STsymboliterator_t *iterator;
    FILE *file;

    DBUG_ENTER ("SerializeSymbolTable");

    file = WriteOpen ("%s/symboltable.c", tmp_dirname);

    GenerateSerFileHead (file);

    GenerateSerSymbolTableHead (module, file);

    iterator = STSymbolIteratorGet (table);

    while (STSymbolIteratorHasMore (iterator)) {
        SerializeSymbolTableSymbol (STSymbolIteratorNext (iterator), table, file);
    }

    iterator = STSymbolIteratorRelease (iterator);

    GenerateSerSymbolTableTail (module, file);

    fclose (file);

    DBUG_VOID_RETURN;
}

static void
GenerateSerDependencyTableHead (node *module, FILE *file)
{
    DBUG_ENTER ("GenerateSerDependencyTableHead");

    fprintf (file, "/* generated by sac2c %s */\n\n", version_id);
    fprintf (file, "void *__%s__DEPTAB() {\n", MODUL_NAME (module));
    fprintf (file, "void *result = (void *) 0;\n");

    DBUG_VOID_RETURN;
}

static void
GenerateSerDependencyTableTail (node *module, FILE *file)
{
    DBUG_ENTER ("GenerateSerDependencyTableTail");

    fprintf (file, "return(result);\n}\n");

    DBUG_VOID_RETURN;
}

static void *
SerTableEntriesFoldFun (const char *val, SStype_t kind, void *rest)
{
    str_buf *result;

    DBUG_ENTER ("SerTableEntriesFoldFun");

    switch (kind) {
    case SS_saclib:
    case SS_extlib:
        result = StrBufprintf ((str_buf *)rest, "result = SSAdd( \"%s\", %d, result);\n",
                               val, kind);
        break;
    default:
        break;
    }

    DBUG_RETURN (result);
}

static void
GenerateSerDependencyTableEntries (node *module, FILE *file)
{
    str_buf *buffer;
    char *string;

    DBUG_ENTER ("GenerateSerDependencyTableEntries");

    buffer = StrBufCreate (4096);

    buffer = SSFold (&SerTableEntriesFoldFun, MODUL_DEPENDENCIES (module), buffer);

    string = StrBuf2String (buffer);

    fprintf (file, string);

    string = Free (string);
    buffer = StrBufFree (buffer);

    DBUG_VOID_RETURN;
}

static void
SerializeDependencyTable (node *module)
{
    FILE *file;

    DBUG_ENTER ("SerializeDependencyTable");

    file = WriteOpen ("%s/dependencytable.c", tmp_dirname);

    GenerateSerFileHead (file);

    GenerateSerDependencyTableHead (module, file);

    GenerateSerDependencyTableEntries (module, file);

    GenerateSerDependencyTableTail (module, file);

    fclose (file);

    DBUG_VOID_RETURN;
}

static void
GenerateSerFunTypeSignature (char *funname, node *args)
{
    DBUG_ENTER ("GenerateSerFunTypeSignature");

    while (args != NULL) {
        strcat (funname, "_");
        strcat (funname, Type2String (ARG_TYPE (args), 2, TRUE));

        args = ARG_NEXT (args);
    }

    DBUG_VOID_RETURN;
}

const char *
GenerateSerFunName (STentrytype_t type, node *node)
{
    static char result[MAX_FUN_NAME_LEN];
    char *tmp;

    DBUG_ENTER ("GenerateSerFunName");

    switch (type) {
    case SET_funbody:
    case SET_wrapperbody:
        snprintf (result, MAX_FUN_NAME_LEN, "SBDY_%s_%s_%d_", FUNDEF_MOD (node),
                  FUNDEF_NAME (node), FUNDEF_STATUS (node));

        GenerateSerFunTypeSignature (result, FUNDEF_ARGS (node));

        break;
    case SET_funhead:
    case SET_wrapperhead:
        snprintf (result, MAX_FUN_NAME_LEN, "SHD_%s_%s_%d_", FUNDEF_MOD (node),
                  FUNDEF_NAME (node), FUNDEF_STATUS (node));

        GenerateSerFunTypeSignature (result, FUNDEF_ARGS (node));

        break;
    case SET_typedef:
        snprintf (result, MAX_FUN_NAME_LEN, "STD_%s_%s_", TYPEDEF_MOD (node),
                  TYPEDEF_NAME (node));
        break;
    case SET_objdef:
        snprintf (result, MAX_FUN_NAME_LEN, "SOD_%s_%s_", OBJDEF_MOD (node),
                  OBJDEF_NAME (node));
        break;
    default:
        DBUG_ASSERT (0, "Unexpected symboltype found!");
        break;
    }

    DBUG_PRINT ("SER", ("Generated new function name: %s", result));

    tmp = ReplaceSpecialCharacters (result);
    strcpy (result, tmp);

    tmp = Free (tmp);

    DBUG_PRINT ("SER", ("Final function name: %s", result));

    DBUG_RETURN (result);
}

static void
GenerateSerFunHead (node *elem, STentrytype_t type, info *info)
{
    DBUG_ENTER ("GenerateSerFunBodyHead");

    fprintf (INFO_SER_FILE (info), "void *%s()", GenerateSerFunName (type, elem));
    fprintf (INFO_SER_FILE (info), "{\n");
    fprintf (INFO_SER_FILE (info), "void *result;\n");
    fprintf (INFO_SER_FILE (info), "void *stack;\n");
    fprintf (INFO_SER_FILE (info), "result = DROP( x");

    DBUG_VOID_RETURN;
}

static void
GenerateSerFunMiddle (node *elem, STentrytype_t type, info *info)
{
    DBUG_ENTER ("GenerateSerFunMiddle");

    fprintf (INFO_SER_FILE (info), ");\nstack = SerializeBuildSerStack( result);\n");

    DBUG_VOID_RETURN;
}

static void
GenerateSerFunTail (node *elem, STentrytype_t type, info *info)
{
    DBUG_ENTER ("GenerateSerFunBodyTail");

    fprintf (INFO_SER_FILE (info), "return( result);\n}\n");

    DBUG_VOID_RETURN;
}

static void
SerializeFundefBody (node *fundef, info *info)
{
    STvisibility_t vis;
    DBUG_ENTER ("SerializeFundefBody");

    INFO_SER_STACK (info) = SerializeBuildSerStack (FUNDEF_BODY (fundef));

    if (GET_FLAG (FUNDEF, fundef, IS_EXPORTED)) {
        vis = SVT_exported;
    } else if (GET_FLAG (FUNDEF, fundef, IS_PROVIDED)) {
        vis = SVT_provided;
    } else {
        vis = SVT_local;
    }

    STAdd (FUNDEF_NAME (fundef), vis, GenerateSerFunName (SET_funbody, fundef),
           (FUNDEF_STATUS (fundef) == ST_wrapperfun) ? SET_wrapperbody : SET_funbody,
           INFO_SER_TABLE (info));

    GenerateSerFunHead (fundef, SET_funbody, info);

    FUNDEF_BODY (fundef) = StartSerializeTraversal (FUNDEF_BODY (fundef), info);

    GenerateSerFunMiddle (fundef, SET_funbody, info);

    FUNDEF_BODY (fundef) = StartSerializeLinkTraversal (FUNDEF_BODY (fundef), info);

    GenerateSerFunTail (fundef, SET_funbody, info);

    INFO_SER_STACK (info) = SerStackDestroy (INFO_SER_STACK (info));

    DBUG_VOID_RETURN;
}

static void
SerializeFundefHead (node *fundef, info *info)
{
    STvisibility_t vis;

    DBUG_ENTER ("SerializeFundefHead");

    INFO_SER_STACK (info) = SerializeBuildSerStack (fundef);

    if (GET_FLAG (FUNDEF, fundef, IS_EXPORTED)) {
        vis = SVT_exported;
    } else if (GET_FLAG (FUNDEF, fundef, IS_PROVIDED)) {
        vis = SVT_provided;
    } else {
        vis = SVT_local;
    }

    FUNDEF_SYMBOLNAME (fundef) = StringCopy (GenerateSerFunName (SET_funhead, fundef));

    STAdd (FUNDEF_NAME (fundef), vis, FUNDEF_SYMBOLNAME (fundef),
           (FUNDEF_STATUS (fundef) == ST_wrapperfun) ? SET_wrapperhead : SET_funhead,
           INFO_SER_TABLE (info));

    GenerateSerFunHead (fundef, SET_funhead, info);

    fundef = StartSerializeTraversal (fundef, info);

    GenerateSerFunMiddle (fundef, SET_funhead, info);

    fundef = StartSerializeLinkTraversal (fundef, info);

    GenerateSerFunTail (fundef, SET_funhead, info);

    INFO_SER_STACK (info) = SerStackDestroy (INFO_SER_STACK (info));

    DBUG_VOID_RETURN;
}

static void
SerializeTypedef (node *tdef, info *info)
{
    STvisibility_t vis;

    DBUG_ENTER ("SerializeTypedef");

    INFO_SER_STACK (info) = SerializeBuildSerStack (tdef);

    TYPEDEF_SYMBOLNAME (tdef) = StringCopy (GenerateSerFunName (SET_typedef, tdef));

    if (GET_FLAG (TYPEDEF, tdef, IS_EXPORTED)) {
        vis = SVT_exported;
    } else if (GET_FLAG (TYPEDEF, tdef, IS_PROVIDED)) {
        vis = SVT_provided;
    } else {
        vis = SVT_local;
    }

    STAdd (TYPEDEF_NAME (tdef), vis, TYPEDEF_SYMBOLNAME (tdef), SET_typedef,
           INFO_SER_TABLE (info));

    GenerateSerFunHead (tdef, SET_typedef, info);

    tdef = StartSerializeTraversal (tdef, info);

    GenerateSerFunMiddle (tdef, SET_typedef, info);

    tdef = StartSerializeLinkTraversal (tdef, info);

    GenerateSerFunTail (tdef, SET_typedef, info);

    INFO_SER_STACK (info) = SerStackDestroy (INFO_SER_STACK (info));

    DBUG_VOID_RETURN;
}

static void
SerializeObjdef (node *objdef, info *info)
{
    STvisibility_t vis;

    DBUG_ENTER ("SerializeObjdef");

    INFO_SER_STACK (info) = SerializeBuildSerStack (objdef);

    TYPEDEF_SYMBOLNAME (objdef) = StringCopy (GenerateSerFunName (SET_objdef, objdef));

    if (GET_FLAG (OBJDEF, objdef, IS_EXPORTED)) {
        vis = SVT_exported;
    } else if (GET_FLAG (OBJDEF, objdef, IS_PROVIDED)) {
        vis = SVT_provided;
    } else {
        vis = SVT_local;
    }

    STAdd (TYPEDEF_NAME (objdef), vis, TYPEDEF_SYMBOLNAME (objdef), SET_objdef,
           INFO_SER_TABLE (info));

    GenerateSerFunHead (objdef, SET_objdef, info);

    objdef = StartSerializeTraversal (objdef, info);

    GenerateSerFunMiddle (objdef, SET_objdef, info);

    objdef = StartSerializeLinkTraversal (objdef, info);

    GenerateSerFunTail (objdef, SET_objdef, info);

    INFO_SER_STACK (info) = SerStackDestroy (INFO_SER_STACK (info));

    DBUG_VOID_RETURN;
}

void
SerializeModule (node *module)
{
    funtab *store_tab;
    info *info;

    DBUG_ENTER ("SerializeModule");

    DBUG_PRINT ("SER", ("Starting serialization run"));

    info = MakeInfo ();

    INFO_SER_FILE (info) = WriteOpen ("%s/serialize.c", tmp_dirname);

    GenerateSerFileHead (INFO_SER_FILE (info));

    store_tab = act_tab;
    act_tab = ser_tab;

    Trav (module, info);

    act_tab = store_tab;

    fclose (INFO_SER_FILE (info));
    INFO_SER_FILE (info) = NULL;

    SerializeSymbolTable (module, INFO_SER_TABLE (info));
    SerializeDependencyTable (module);

    info = FreeInfo (info);

    DBUG_VOID_RETURN;
}

void
SerializeFundefLink (node *fundef, FILE *file)
{
    DBUG_ENTER ("SerializeFundefLink");

    if (fundef == NULL) {
        fprintf (file, "NULL");
    } else {
        fprintf (file, "DeserializeLookupFunction( \"%s\", \"%s\")", FUNDEF_MOD (fundef),
                 GenerateSerFunName (SET_funhead, fundef));
    }

    DBUG_VOID_RETURN;
}

node *
SERFundef (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("SERFundef");

    DBUG_PRINT ("SER", ("Serializing function %s", FUNDEF_NAME (arg_node)));

    /*
     * only serialize functions that are not available
     * in another module
     */
    if (GET_FLAG (FUNDEF, arg_node, IS_LOCAL)) {
        SerializeFundefHead (arg_node, arg_info);

        /*
         * there might be functions without a body
         */
        if (FUNDEF_BODY (arg_node) != NULL) {
            SerializeFundefBody (arg_node, arg_info);
        }
    }

    if (FUNDEF_NEXT (arg_node) != NULL) {
        FUNDEF_NEXT (arg_node) = Trav (FUNDEF_NEXT (arg_node), arg_info);
    }

    DBUG_RETURN (arg_node);
}

node *
SERTypedef (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("SERTypedef");

    DBUG_PRINT ("SER", ("Serializing typedef %s", TYPEDEF_NAME (arg_node)));

    /*
     * Only serialize typedefs that are not available in another
     * module
     */
    if (GET_FLAG (TYPEDEF, arg_node, IS_LOCAL)) {
        SerializeTypedef (arg_node, arg_info);
    }

    if (TYPEDEF_NEXT (arg_node) != NULL) {
        TYPEDEF_NEXT (arg_node) = Trav (TYPEDEF_NEXT (arg_node), arg_info);
    }

    DBUG_RETURN (arg_node);
}

node *
SERObjdef (node *arg_node, info *arg_info)
{
    DBUG_ENTER ("SERObjdef");

    DBUG_PRINT ("SER", ("Serializing objdef %s", OBJDEF_NAME (arg_node)));

    /*
     * only serialize objdefs that are not available in another
     * module
     */
    if (OBJDEF_SYMBOLNAME (arg_node) == NULL) {
        SerializeObjdef (arg_node, arg_info);
    }

    if (OBJDEF_NEXT (arg_node) != NULL) {
        OBJDEF_NEXT (arg_node) = Trav (OBJDEF_NEXT (arg_node), arg_info);
    }

    DBUG_RETURN (arg_node);
}
