/*
 *
 * $Log$
 * Revision 1.6  2004/06/30 12:20:07  khf
 * WLPGfundef(): application of Constant Folding added
 * (PH_wlpartgen)
 *
 * Revision 1.5  2004/05/28 16:30:10  sbs
 * *** empty log message ***
 *
 * Revision 1.4  2004/04/08 08:13:25  khf
 * some corrections and new startfunction WLPartitionGenerationOPT
 * added
 *
 * Revision 1.3  2004/03/02 09:21:43  khf
 * some corrections and WLPGlet added
 *
 * Revision 1.2  2004/02/26 13:11:01  khf
 * WLPartitionGeneration implemented in parts (but not tested)
 *
 * Revision 1.1  2004/02/25 13:16:58  khf
 * Initial revision
 *
 *
 */

/*
 * compiler phase: Withloop Partition Generation (WLPG)
 *
 *
 */
/*******************************************************************************
 *  Usage of arg_info:
 *  - node[0] : WL      : reference to base node of current WL (N_Nwith)
 *  - node[1] : FUNDEF  : pointer to last fundef node. needed to access vardecs.
 *  - node[2] : LET     : pointer to N_let node of current WL.
 *                        LET_EXPR(ID) == INFO_WLPG_WL.
 *  - node[3] : NASSIGNS: pointer to a list of new assigns, which where needed
 *                        to build structural constants and had to be inserted
 *                        in front of the considered with-loop.
 *  - counter : GENPROB : pointer to the status of the considered generator
 *                        concerning coverage of the entire range
 *  - int_data: GENSHP  : pointer to the status of the bounds, step and width
 *                        of the considered generator concerning shape
 *
 ******************************************************************************/

#define INFO_WLPG_WL(n) (n->node[0])
#define INFO_WLPG_FUNDEF(n) (n->node[1])
#define INFO_WLPG_LET(n) (n->node[2])
#define INFO_WLPG_NASSIGNS(n) (n->node[3])
#define INFO_WLPG_MODUL(n) (n->node[4])
#define INFO_WLPG_GENPROP(n) (n->counter)
#define INFO_WLPG_GENSHP(n) (n->int_data)

#include <stdio.h>
#include <stdlib.h>

#include "types.h"
#include "tree_basic.h"
#include "tree_compound.h"
#include "internal_lib.h"
#include "free.h"
#include "DupTree.h"
#include "Error.h"
#include "globals.h"
#include "dbug.h"
#include "traverse.h"
#include "constants.h"
#include "SSAConstantFolding.h"
#include "ssa.h"
#include "WLPartitionGeneration.h"

typedef enum { GPT_empty, GPT_full, GPT_partial, GPT_unknown } gen_prop_t;

typedef enum {
    GV_constant,
    GV_struct_constant,
    GV_known_shape,
    GV_unknown_shape
} gen_shape_t;

/** <!--********************************************************************-->
 *
 * @fn node *CreateStructConstant( node *expr, node *nassigns)
 *
 *   @brief A structural constant is freshly generated by means of (nassigns)
 *          and (*expr) is modified to point to the new node.
 *          The old one is freed!
 *
 *   @param  node *expr     :  expr
 *           node *nassigns :  a chained list of N_assign nodes
 *   @return node *         :  updated expr
 ******************************************************************************/
static node *
CreateStructConstant (node *expr, node *nassigns)
{
    node *tmp1, *tmp2, *idn, *iterator;
    ids *tmp_ids;
    shpseg *nshpseg;
    int dim = 0;
    char *varname;

    DBUG_ENTER ("CreateStructConstant");

    DBUG_ASSERT ((nassigns != NULL), "NASSIGNS is empty");

    tmp1 = NULL;
    tmp2 = NULL;
    iterator = nassigns;

    while (iterator) {
        tmp_ids = LET_IDS (ASSIGN_INSTR (iterator));
        varname = StringCopy (IDS_NAME (tmp_ids));

        idn = MakeId (varname, NULL, ST_regular);
        ID_VARDEC (idn) = IDS_VARDEC (tmp_ids);
        ID_AVIS (idn) = IDS_AVIS (tmp_ids);

        if (tmp1) {
            EXPRS_NEXT (tmp2) = MakeExprs (idn, NULL);
            tmp2 = EXPRS_NEXT (tmp2);
        } else {
            tmp1 = MakeExprs (idn, tmp1);
            tmp2 = tmp1;
        }

        iterator = ASSIGN_NEXT (iterator);
        dim++;
    }

    tmp1 = MakeFlatArray (tmp1);
    nshpseg = MakeShpseg (MakeNums (dim, NULL));
    ARRAY_TYPE (tmp1) = MakeTypes (N_id, 1, nshpseg, NULL, NULL);
    expr = FreeTree (expr);
    expr = tmp1;

    DBUG_RETURN (expr);
}

/** <!--********************************************************************-->
 *
 * @fn node *AppendAssigns( node *nassigns, node *oassigns)
 *
 *   @brief appends nassigns on oassigns.
 *
 *   @param  node *nassigns :  a new chained list of N_assign nodes
 *           node *oassigns :  a old chained list of N_assign nodes
 *   @return node *         :  updated oassigns
 ******************************************************************************/
static node *
AppendAssigns (node *nassigns, node *oassigns)
{
    node *iterator;

    DBUG_ENTER ("AppendAssigns");

    if (oassigns) {
        iterator = oassigns;
        while (ASSIGN_NEXT (iterator)) {
            iterator = ASSIGN_NEXT (iterator);
        }
        ASSIGN_NEXT (iterator) = nassigns;
    } else {
        oassigns = nassigns;
    }

    DBUG_RETURN (oassigns);
}

/** <!--********************************************************************-->
 *
 * @fn node CreateEntryFlatArray(int entry, int number, types *type)
 *
 *   @brief creates an flat array with 'number' elements consisting of
 *          'entry'
 *
 *   @param  int entry   : entry within the new array
 *           int number  : number of elements in the new array
 *           types *type : type of the elements
 *   @return node *      : N_array
 ******************************************************************************/
static node *
CreateEntryFlatArray (int entry, int number, types *type)
{
    node *tmp;
    int i;

    DBUG_ENTER ("CreateOneArray");

    DBUG_ASSERT ((number > 0), "dim is <= 0");

    tmp = NULL;
    for (i = 0; i < number; i++) {
        tmp = MakeExprs (MakeNum (entry), tmp);
    }
    tmp = MakeFlatArray (tmp);
    ARRAY_TYPE (tmp) = DupAllTypes (type);

    ARRAY_ISCONST (tmp) = TRUE;
    ARRAY_VECTYPE (tmp) = TYPES_BASETYPE (ARRAY_TYPE (tmp));
    ARRAY_VECLEN (tmp) = number;
    ARRAY_CONSTVEC (tmp)
      = Array2Vec (TYPES_BASETYPE (ARRAY_TYPE (tmp)), ARRAY_AELEMS (tmp), NULL);
    DBUG_RETURN (tmp);
}

/** <!--********************************************************************-->
 *
 * @fn node *CreateNewPart(node * lb, node *ub, node * step, node *width,
 *                        node *withid, node *coden)
 *
 *   @brief creates a new N_Npart
 *
 *   @param  node *lb,*ub       : bound of new part
 *           node *step, *width : step, width of new part
 *           node *withid       : withid of new part
 *           node *coden        : Pointer of N_Ncode node where the
 *                                new generator shall point to.
 *   @return node *             : N_Npart
 ******************************************************************************/
node *
CreateNewPart (node *lb, node *ub, node *step, node *width, node *withid, node *coden)
{
    node *genn, *partn;

    DBUG_ENTER ("CreateNewPart");

    /* create tree structures */
    genn = MakeNGenerator (DupTree (lb), DupTree (ub), F_le, F_lt, DupTree (step),
                           DupTree (width));
    partn = MakeNPart (DupTree (withid), genn, coden);

    DBUG_RETURN (partn);
}

/** <!--********************************************************************-->
 *
 * @fn int NormalizeStepWidth(node **step, node **width)
 *
 *   @brief normalizes step and width. There are several forbidden and
 *          ambiguous combinations of bounds, step (s) and width (w).
 *
 *          allowed is the following (for each component):
 *          - w < s and s > 1 or
 *          - w == 1 and s == 1
 *
 *          transformations:
 *          - w == s: set w = s = 1 (componentwise)
 *          - vector s == 1 and vector w == 1: set both to NULL
 *          - vector s != NULL and vector w == NULL: create vector w = 1.
 *
 *
 *          errors:
 *          - w > s        (error no 1)
 *          - 1 > w        (error no 2)
 *          - w without s  (error no 3)
 *
 *   @param  node **step  :  step vector
 *           node **width :  width vektor
 *   @return int         :  returns 0 if no error was detected, else error no
 *                          (see above).
 ******************************************************************************/
static int
NormalizeStepWidth (node **step, node **width)
{
    node *stp, *wth;
    shpseg *nshpseg;
    int stpnum, wthnum, veclen;
    int error = 0, is_1 = 1;

    DBUG_ENTER ("NormalizeStepWidth");

    if ((*width) != NULL && (*step) == NULL) {
        error = 3;
    } else if ((*step) != NULL) {

        if ((*width) == NULL) {
            /*  create width with constant 1 */
            if (ARRAY_ISCONST ((*step)))
                veclen = ARRAY_VECLEN ((*step));
            else
                veclen = CountExprs (ARRAY_AELEMS ((*step)));

            nshpseg = MakeShpseg (MakeNums (veclen, NULL));
            (*width) = CreateEntryFlatArray (1, veclen,
                                             MakeTypes (T_int, 1, nshpseg, NULL, NULL));
        }

        stp = ARRAY_AELEMS ((*step));
        wth = ARRAY_AELEMS ((*width));

        while (stp && !error) {
            DBUG_ASSERT ((wth != NULL), "dimensionality differs in step and width!");

            if ((NODE_TYPE (EXPRS_EXPR (stp)) == N_num)
                && (NODE_TYPE (EXPRS_EXPR (wth)) == N_num)) {

                stpnum = NUM_VAL (EXPRS_EXPR (stp));
                wthnum = NUM_VAL (EXPRS_EXPR (wth));

                if (wthnum > stpnum)
                    error = 1;
                else if (1 > wthnum)
                    error = 2;
                else if (wthnum == stpnum && stpnum != 1)
                    NUM_VAL (EXPRS_EXPR (stp)) = NUM_VAL (EXPRS_EXPR (wth)) = stpnum = 1;

                is_1 = is_1 && 1 == stpnum;
            } else if ((NODE_TYPE (EXPRS_EXPR (stp)) == N_id)
                       && (NODE_TYPE (EXPRS_EXPR (wth)) == N_id)) {
                if (!strcmp (ID_NAME (EXPRS_EXPR (stp)), ID_NAME (EXPRS_EXPR (wth)))) {
                    EXPRS_EXPR (stp) = FreeTree (EXPRS_EXPR (stp));
                    EXPRS_EXPR (stp) = MakeNum (1);
                    EXPRS_EXPR (wth) = FreeTree (EXPRS_EXPR (wth));
                    EXPRS_EXPR (wth) = MakeNum (1);
                    is_1 = is_1 && TRUE;
                } else {
                    is_1 = FALSE;
                }
            } else {
                is_1 = FALSE;
            }

            stp = EXPRS_NEXT (stp);
            wth = EXPRS_NEXT (wth);
        }

        /* if both vectors are 1 this is equivalent to no grid */

        if (!error && is_1) {
            (*step) = FreeTree (*step);
            (*width) = FreeTree (*width);
        }
    }

    DBUG_RETURN (error);
}

/** <!--********************************************************************-->
 *
 * @fn node *AppendPart2WL(node * wln, node *partn)
 *
 *   @brief append N_Npart npart to the existing parts of
 *          the N_Nwith node wln
 *
 *   @param  node *wln    : N_Nwith
 *           node *npart  : N_Npart
 *   @return node *       : modified N_Nwith
 ******************************************************************************/
static node *
AppendPart2WL (node *wln, node *partn)
{
    node *parts;
    int no_parts;

    DBUG_ENTER ("AppendPart2WL");

    parts = NWITH_PART (wln);
    /* at least one part exists */
    no_parts = 1;

    while (NPART_NEXT (parts)) {
        parts = NPART_NEXT (parts);
        no_parts++;
    }

    NPART_NEXT (parts) = partn;
    no_parts++;
    NWITH_PARTS (wln) = no_parts;

    DBUG_RETURN (wln);
}

/** <!--********************************************************************-->
 *
 * @fn node *CutSlices( node *ls, node *us, node *l, node *u, int dim,
 *                       node *wln, node *coden)
 *
 *   @brief  Creates a (full) partition by adding new N_Ngenerator nodes
 *           to the N_Nwith node.
 *           If the known part is a grid, this is ignored here (so the
 *           resulting N_Nwith node may still not be a full partition,
 *           see CompleteGrid()).
 *
 *   @param  node *ls, *us : bounds of the whole array
 *           node *l, *u   : bounds of the given part
 *           int dim       : number of elements of ls, us, l, u
 *           node *wln     : Pointer of N_Nwith node where the new generators
 *                           shall be inserted.
 *           node *coden   : Pointer of N_Ncode node where the new generators
 *                           shall point to.
 *   @return node *        : modified N_Nwith
 ******************************************************************************/
static node *
CutSlices (node *ls, node *us, node *l, node *u, int dim, node *wln, node *coden)
{
    node *lsc, *usc, *le, *ue, *lsce, *usce, *partn, *withidn, *ubn, *lbn;
    int i, d, lnum, lscnum, unum, uscnum;

    DBUG_ENTER ("CutSlices");

    /* create local copies of the arrays which atr modified here*/
    lsc = DupTree (ls);
    usc = DupTree (us);

    le = ARRAY_AELEMS (l);
    lsce = ARRAY_AELEMS (lsc);
    ue = ARRAY_AELEMS (u);
    usce = ARRAY_AELEMS (usc);

    withidn = DupTree (NPART_WITHID (NWITH_PART (wln)));

    for (d = 0; d < dim; d++) {
        /* Check whether there is a cuboid above (below) the given one. */

        if (NODE_TYPE (EXPRS_EXPR (le)) == N_num) {
            lnum = NUM_VAL (EXPRS_EXPR (le));
            lscnum = NUM_VAL (EXPRS_EXPR (lsce));
            if (lnum > lscnum) {
                partn = CreateNewPart (lsc, usc, NULL, NULL, withidn, coden);
                ubn = ARRAY_AELEMS (NPART_BOUND2 (partn));
                for (i = 0; i < d; i++) {
                    ubn = EXPRS_NEXT (ubn);
                }
                if (NODE_TYPE (EXPRS_EXPR (ubn)) == N_num) {
                    NUM_VAL (EXPRS_EXPR (ubn)) = lnum;
                } else {
                    EXPRS_EXPR (ubn) = FreeTree (EXPRS_EXPR (ubn));
                    EXPRS_EXPR (ubn) = DupTree (EXPRS_EXPR (le));
                }
                wln = AppendPart2WL (wln, partn);
            }
        } else {
            partn = CreateNewPart (lsc, usc, NULL, NULL, withidn, coden);
            ubn = ARRAY_AELEMS (NPART_BOUND2 (partn));
            for (i = 0; i < d; i++) {
                ubn = EXPRS_NEXT (ubn);
            }
            EXPRS_EXPR (ubn) = FreeTree (EXPRS_EXPR (ubn));
            EXPRS_EXPR (ubn) = DupTree (EXPRS_EXPR (le));
            if (ARRAY_ISCONST (NPART_BOUND2 (partn))) {
                ARRAY_ISCONST (NPART_BOUND2 (partn)) = FALSE;
                ARRAY_CONSTVEC (NPART_BOUND2 (partn))
                  = Free (ARRAY_CONSTVEC (NPART_BOUND2 (partn)));
            }
            wln = AppendPart2WL (wln, partn);
        }

        if ((NODE_TYPE (EXPRS_EXPR (ue)) == N_num)
            && (NODE_TYPE (EXPRS_EXPR (usce)) == N_num)) {
            unum = NUM_VAL (EXPRS_EXPR (ue));
            uscnum = NUM_VAL (EXPRS_EXPR (usce));
            if (unum < uscnum) {
                partn = CreateNewPart (lsc, usc, NULL, NULL, withidn, coden);
                lbn = ARRAY_AELEMS (NPART_BOUND1 (partn));
                for (i = 0; i < d; i++) {
                    lbn = EXPRS_NEXT (lbn);
                }
                NUM_VAL (EXPRS_EXPR (lbn)) = unum;
                wln = AppendPart2WL (wln, partn);
            }
        } else {
            partn = CreateNewPart (lsc, usc, NULL, NULL, withidn, coden);
            lbn = ARRAY_AELEMS (NPART_BOUND1 (partn));
            for (i = 0; i < d; i++) {
                lbn = EXPRS_NEXT (lbn);
            }
            EXPRS_EXPR (lbn) = FreeTree (EXPRS_EXPR (lbn));
            EXPRS_EXPR (lbn) = DupTree (EXPRS_EXPR (ue));
            if ((NODE_TYPE (EXPRS_EXPR (lbn)) != N_num)
                && (ARRAY_ISCONST (NPART_BOUND1 (partn)))) {
                ARRAY_ISCONST (NPART_BOUND1 (partn)) = FALSE;
                ARRAY_CONSTVEC (NPART_BOUND1 (partn))
                  = Free (ARRAY_CONSTVEC (NPART_BOUND1 (partn)));
            }
            wln = AppendPart2WL (wln, partn);
        }

        /* and modifiy array bounds to continue with next dimension */
        if (NODE_TYPE (EXPRS_EXPR (le)) == N_num) {
            NUM_VAL (EXPRS_EXPR (lsce)) = NUM_VAL (EXPRS_EXPR (le));
        } else {
            EXPRS_EXPR (lsce) = FreeTree (EXPRS_EXPR (lsce));
            EXPRS_EXPR (lsce) = DupTree (EXPRS_EXPR (le));
            if (ARRAY_ISCONST (lsc)) {
                ARRAY_ISCONST (lsc) = FALSE;
                ARRAY_CONSTVEC (lsc) = Free (ARRAY_CONSTVEC (lsc));
            }
        }

        if ((NODE_TYPE (EXPRS_EXPR (ue)) == N_num)
            && (NODE_TYPE (EXPRS_EXPR (usce)) == N_num)) {
            NUM_VAL (EXPRS_EXPR (usce)) = NUM_VAL (EXPRS_EXPR (ue));
        } else {
            EXPRS_EXPR (usce) = FreeTree (EXPRS_EXPR (usce));
            EXPRS_EXPR (usce) = DupTree (EXPRS_EXPR (ue));
            if ((NODE_TYPE (EXPRS_EXPR (usce)) != N_num) && (ARRAY_ISCONST (usc))) {
                ARRAY_ISCONST (usc) = FALSE;
                ARRAY_CONSTVEC (usc) = Free (ARRAY_CONSTVEC (usc));
            }
        }

        le = EXPRS_NEXT (le);
        lsce = EXPRS_NEXT (lsce);
        ue = EXPRS_NEXT (ue);
        usce = EXPRS_NEXT (usce);
    }

    lsc = FreeTree (lsc);
    usc = FreeTree (usc);
    withidn = FreeTree (withidn);

    DBUG_RETURN (wln);
}

/** <!--********************************************************************-->
 *
 * @fn node *CompleteGrid( node *ls, node *us, node *step, node *width,
 *                         int dim, node *wln, node *coden, node *arg_info)
 *
 *   @brief  adds new parts to N_Nwith which specify the elements
 *           left out by a grid.
 *
 *   @param  node *ls,*us       : bounds of the given part
 *           node *step, *width :
 *           int dim            : number of elements of ls, us
 *           node *wln          : N_Nwith where to add the new parts.
 *                                If ig != NULL, the same pointer is returned.
 *           node *coden        : Pointer of N_Ncode node where the new
 *                                generators shall point to.
 *           node *arg_info     : N_INFO is needed to create new vars
 *   @return intern_gen *       : chain of intern_gen struct
 ******************************************************************************/
static node *
CompleteGrid (node *ls, node *us, node *step, node *width, int dim, node *wln,
              node *coden, node *arg_info)
{
    node *nw, *stpe, *wthe, *nwe, *partn, *withidn, *lbn, *wthn, *tmp1, *tmp2, *vardec,
      *nassign, *idn;
    int i, d, stpnum, wthnum;
    ids *_ids;
    char *nvarname;

    DBUG_ENTER ("CompleteGrid");

    /* create local copies of the arrays which atr modified here*/
    nw = DupTree (step);

    stpe = ARRAY_AELEMS (step);
    wthe = ARRAY_AELEMS (width);
    nwe = ARRAY_AELEMS (nw);

    withidn = DupTree (NPART_WITHID (NWITH_PART (wln)));

    for (d = 0; d < dim; d++) {

        if ((NODE_TYPE (EXPRS_EXPR (stpe)) == N_num)
            && (NODE_TYPE (EXPRS_EXPR (wthe)) == N_num)) {
            stpnum = NUM_VAL (EXPRS_EXPR (stpe));
            wthnum = NUM_VAL (EXPRS_EXPR (wthe));

            if (stpnum > wthnum) { /* create new grids */

                partn = CreateNewPart (ls, us, step, nw, withidn, coden);
                lbn = ARRAY_AELEMS (NPART_BOUND1 (partn));
                wthn = ARRAY_AELEMS (NPART_WIDTH (partn));

                for (i = 0; i < d; i++) {
                    wthn = EXPRS_NEXT (wthn);
                    lbn = EXPRS_NEXT (lbn);
                }

                if (NODE_TYPE (EXPRS_EXPR (lbn)) == N_num) {
                    NUM_VAL (EXPRS_EXPR (lbn)) = NUM_VAL (EXPRS_EXPR (lbn)) + wthnum;
                } else {
                    nvarname = TmpVarName (ID_NAME (EXPRS_EXPR (lbn)));
                    _ids = MakeIds (nvarname, NULL, ST_regular);
                    vardec = MakeVardec (StringCopy (nvarname),
                                         DupOneTypes (ID_TYPE (EXPRS_EXPR (lbn))), NULL);
                    IDS_VARDEC (_ids) = vardec;
                    IDS_AVIS (_ids) = VARDEC_AVIS (vardec);

                    INFO_WLPG_FUNDEF (arg_info)
                      = AddVardecs (INFO_WLPG_FUNDEF (arg_info), vardec);

                    /* the identifier to add wthnum to */
                    tmp1 = DupTree (EXPRS_EXPR (lbn));
                    /* N_num wthnum */
                    tmp2 = MakeExprs (DupTree (EXPRS_EXPR (wthe)), NULL);

                    tmp1 = MakePrf (F_add_SxS, MakeExprs (tmp1, tmp2));

                    nassign = MakeAssign (MakeLet (tmp1, _ids), NULL);
                    INFO_WLPG_NASSIGNS (arg_info)
                      = AppendAssigns (nassign, INFO_WLPG_NASSIGNS (arg_info));

                    idn = MakeId (StringCopy (nvarname), NULL, ST_regular);
                    ID_VARDEC (idn) = IDS_VARDEC (_ids);
                    ID_AVIS (idn) = IDS_AVIS (_ids);

                    EXPRS_EXPR (lbn) = FreeTree (EXPRS_EXPR (lbn));
                    EXPRS_EXPR (lbn) = idn;
                }
                NUM_VAL (EXPRS_EXPR (wthn)) = stpnum - wthnum;
                i = NormalizeStepWidth (&(NPART_STEP (partn)), &(NPART_WIDTH (partn)));
                DBUG_ASSERT (!i, ("internal normalization failure"));

                wln = AppendPart2WL (wln, partn);
            }
        } else {
            partn = CreateNewPart (ls, us, step, nw, withidn, coden);
            lbn = ARRAY_AELEMS (NPART_BOUND1 (partn));
            wthn = ARRAY_AELEMS (NPART_WIDTH (partn));

            for (i = 0; i < d; i++) {
                wthn = EXPRS_NEXT (wthn);
                lbn = EXPRS_NEXT (lbn);
            }

            if ((NODE_TYPE (EXPRS_EXPR (lbn)) == N_num)
                && (NODE_TYPE (EXPRS_EXPR (wthe)) == N_num)) {
                NUM_VAL (EXPRS_EXPR (lbn))
                  = NUM_VAL (EXPRS_EXPR (lbn)) + NUM_VAL (EXPRS_EXPR (wthe));
            } else {
                nvarname = TmpVarName (ID_NAME (EXPRS_EXPR (lbn)));
                _ids = MakeIds (nvarname, NULL, ST_regular);
                vardec = MakeVardec (StringCopy (nvarname),
                                     DupOneTypes (ID_TYPE (EXPRS_EXPR (lbn))), NULL);
                IDS_VARDEC (_ids) = vardec;
                IDS_AVIS (_ids) = VARDEC_AVIS (vardec);

                INFO_WLPG_FUNDEF (arg_info)
                  = AddVardecs (INFO_WLPG_FUNDEF (arg_info), vardec);

                /* the identifier to add current width to */
                tmp1 = DupTree (EXPRS_EXPR (lbn));
                /* current width as N_num or N_id */
                tmp2 = MakeExprs (DupTree (EXPRS_EXPR (wthe)), NULL);

                tmp1 = MakePrf (F_add_SxS, MakeExprs (tmp1, tmp2));

                nassign = MakeAssign (MakeLet (tmp1, _ids), NULL);
                INFO_WLPG_NASSIGNS (arg_info)
                  = AppendAssigns (nassign, INFO_WLPG_NASSIGNS (arg_info));

                idn = MakeId (StringCopy (nvarname), NULL, ST_regular);
                ID_VARDEC (idn) = IDS_VARDEC (_ids);
                ID_AVIS (idn) = IDS_AVIS (_ids);

                EXPRS_EXPR (lbn) = FreeTree (EXPRS_EXPR (lbn));
                EXPRS_EXPR (lbn) = idn;
            }

            if ((NODE_TYPE (EXPRS_EXPR (stpe)) == N_num)
                && (NODE_TYPE (EXPRS_EXPR (wthe)) == N_num)) {
                NUM_VAL (EXPRS_EXPR (wthn))
                  = NUM_VAL (EXPRS_EXPR (stpe)) - NUM_VAL (EXPRS_EXPR (wthe));
            } else {
                nvarname = TmpVarName (ID_NAME (EXPRS_EXPR (wthn)));
                _ids = MakeIds (nvarname, NULL, ST_regular);
                vardec = MakeVardec (StringCopy (nvarname),
                                     DupOneTypes (ID_TYPE (EXPRS_EXPR (wthn))), NULL);
                IDS_VARDEC (_ids) = vardec;
                IDS_AVIS (_ids) = VARDEC_AVIS (vardec);

                INFO_WLPG_FUNDEF (arg_info)
                  = AddVardecs (INFO_WLPG_FUNDEF (arg_info), vardec);

                /* the first identifier */
                tmp1 = DupTree (EXPRS_EXPR (stpe));
                /* the second identifier */
                tmp2 = MakeExprs (DupTree (EXPRS_EXPR (wthe)), NULL);

                tmp1 = MakePrf (F_sub_SxS, MakeExprs (tmp1, tmp2));

                nassign = MakeAssign (MakeLet (tmp1, _ids), NULL);
                INFO_WLPG_NASSIGNS (arg_info)
                  = AppendAssigns (nassign, INFO_WLPG_NASSIGNS (arg_info));

                idn = MakeId (StringCopy (nvarname), NULL, ST_regular);
                ID_VARDEC (idn) = IDS_VARDEC (_ids);
                ID_AVIS (idn) = IDS_AVIS (_ids);

                EXPRS_EXPR (wthn) = FreeTree (EXPRS_EXPR (wthn));
                EXPRS_EXPR (wthn) = idn;
            }

            i = NormalizeStepWidth (&(NPART_STEP (partn)), &(NPART_WIDTH (partn)));
            DBUG_ASSERT (!i, ("internal normalization failure"));

            wln = AppendPart2WL (wln, partn);
        }

        /* and modifiy array bounds to continue with next dimension */
        if ((NODE_TYPE (EXPRS_EXPR (nwe)) == N_num)
            && (NODE_TYPE (EXPRS_EXPR (wthe)) == N_num)) {
            NUM_VAL (EXPRS_EXPR (nwe)) = NUM_VAL (EXPRS_EXPR (wthe));
        } else {
            EXPRS_EXPR (nwe) = FreeTree (EXPRS_EXPR (nwe));
            EXPRS_EXPR (nwe) = DupTree (EXPRS_EXPR (wthe));
            if ((NODE_TYPE (EXPRS_EXPR (nwe)) != N_num) && (ARRAY_ISCONST (nw))) {
                ARRAY_ISCONST (nw) = FALSE;
                ARRAY_CONSTVEC (nw) = Free (ARRAY_CONSTVEC (nw));
            }
        }

        stpe = EXPRS_NEXT (stpe);
        wthe = EXPRS_NEXT (wthe);
    }

    nw = FreeTree (nw);

    DBUG_RETURN (wln);
}

/** <!--********************************************************************-->
 *
 * @fn  node *CreateFullPartition( node *wln, node *arg_info)
 *
 *   @brief  generates full partition if possible:
 *           - if withop is genarray and index vector has as much elements as
 *             dimension of resulting WL (withloop on scalars).
 *           - if withop is modarray: always (needed for compilation phase).
 *           Returns wln.
 *
 *   @param  node *wl       :  N_with node of the WL to transform
 *           node *arg_info :  is needed to access the vardecs of the current
 *                             function
 *   @return node *         :  modified N_with
 ******************************************************************************/
static node *
CreateFullPartition (node *wln, node *arg_info)
{
    node *coden, *idn, *nassign, *tmp1, *tmp2, *array_shape = NULL, *array_null, *vardec,
                                               *nassigns;
    ids *_ids;
    types *type;
    shpseg *oshpseg, *nshpseg;
    char *varname, *nvarname;
    int dim, i, gen_shape = 0;
    bool do_create;

    DBUG_ENTER ("CreateFullPartition");

    do_create = TRUE;

    /*
     * allocate "array_shape"
     */
    switch (NWITH_TYPE (wln)) {
    case WO_modarray: {
        /* create upper array bound */

        oshpseg = Type2Shpseg (ID_TYPE (NWITH_ARRAY (wln)), &dim);

        if (dim > 0) {
            tmp1 = NULL;
            for (i = (dim - 1); i >= 0; i--) {
                tmp1 = MakeExprs (MakeNum (SHPSEG_SHAPE (oshpseg, i)), tmp1);
            }
            array_shape = MakeFlatArray (tmp1);
            nshpseg = MakeShpseg (MakeNums (dim, NULL));
            ARRAY_TYPE (array_shape) = MakeTypes (T_int, 1, nshpseg, NULL, NULL);

            ARRAY_ISCONST (array_shape) = TRUE;
            ARRAY_VECTYPE (array_shape) = TYPES_BASETYPE (ARRAY_TYPE (array_shape));
            ARRAY_VECLEN (array_shape) = dim;
            ARRAY_CONSTVEC (array_shape)
              = Array2Vec (TYPES_BASETYPE (ARRAY_TYPE (array_shape)),
                           ARRAY_AELEMS (array_shape), NULL);

            if (oshpseg != NULL)
                oshpseg = FreeShpseg (oshpseg);
        } else if (dim <= -3) {
            /*
             * < -2: dimension == -2 - DIM and  unknown shape
             * => build structural constant
             */
            nassigns = NULL;

            for (i = (abs (dim) - 3); i >= 0; i--) {
                nvarname = TmpVarName (ID_NAME (NWITH_ARRAY (wln)));
                _ids = MakeIds (nvarname, NULL, ST_regular);
                vardec = MakeVardec (StringCopy (nvarname),
                                     DupOneTypes (ID_TYPE (NWITH_ARRAY (wln))), NULL);
                IDS_VARDEC (_ids) = vardec;
                IDS_AVIS (_ids) = VARDEC_AVIS (vardec);
                INFO_WLPG_FUNDEF (arg_info)
                  = AddVardecs (INFO_WLPG_FUNDEF (arg_info), vardec);

                /* index position for selection */
                tmp1 = MakeNum (i);
                /* the array for selection */
                tmp2 = MakeExprs (DupTree (NWITH_ARRAY (wln)), NULL);
                tmp1 = MakePrf (F_shape_sel, MakeExprs (tmp1, tmp2));

                nassigns = MakeAssign (MakeLet (tmp1, _ids), nassigns);

                /* set correct backref to defining assignment */
                AVIS_SSAASSIGN (IDS_AVIS (_ids)) = nassigns;
            }

            array_shape = CreateStructConstant (array_shape, nassigns);
            INFO_WLPG_NASSIGNS (arg_info)
              = AppendAssigns (nassigns, INFO_WLPG_NASSIGNS (arg_info));
        } else {
            /* dimension unknown */
            array_shape = NULL;
        }
    } break;

    case WO_genarray:
        array_shape = DupTree (NWITH_SHAPE (wln));
        break;

    default:
        DBUG_ASSERT ((0), "illegal NWITH_TYPE found!");
        array_shape = NULL;
        break;
    }
    do_create = (array_shape != NULL);

    /*
     * start creation
     */
    if (do_create) {
        /* create lower array bound */

        /* determine type of expr in the operator (result of body) */
        type = ID_TYPE (NWITH_CEXPR (wln));

        /* get shape of the index vector (generator) */
        gen_shape = IDS_SHAPE (NWITH_VEC (wln), 0);
        nshpseg = MakeShpseg (MakeNums (gen_shape, NULL));
        array_null = CreateEntryFlatArray (0, gen_shape,
                                           MakeTypes (T_int, 1, nshpseg, NULL, NULL));

        /* create code for all new parts */
        if (NWITH_TYPE (wln) == WO_genarray) {
            /* create a zero of the correct type */
            if (sbs == 1) {
                if (NWITHOP_DEFAULT (NWITH_WITHOP (wln)) == NULL) {
                    coden = CreateZeroFromType (type, FALSE, INFO_WLPG_FUNDEF (arg_info));
                } else {
                    coden = DupTree (NWITHOP_DEFAULT (NWITH_WITHOP (wln)));
                }
            } else {
                coden = CreateZeroFromType (type, FALSE, INFO_WLPG_FUNDEF (arg_info));
            }
        } else { /* modarray */
            /*
             * we build NO with-loop here in order to ease optimizations
             *    B = modarray( A, iv, sel( iv, A));   ->   B = A;
             * and to avoid loss of performance
             *    sel( iv, A)   ->   idx_sel( ..., A)
             */
            coden = CreateSel (NWITH_VEC (wln), NWITH_IDS (wln), NWITH_ARRAY (wln), FALSE,
                               INFO_WLPG_FUNDEF (arg_info));
        }

        varname = TmpVar ();
        _ids = MakeIds (varname, NULL, ST_regular);
        vardec = MakeVardec (StringCopy (varname), DupOneTypes (type), NULL);
        IDS_VARDEC (_ids) = vardec;
        IDS_AVIS (_ids) = VARDEC_AVIS (vardec);
        INFO_WLPG_FUNDEF (arg_info) = AddVardecs (INFO_WLPG_FUNDEF (arg_info), vardec);

        /* varname is duplicated here (own mem) */
        idn = MakeId (StringCopy (varname), NULL, ST_regular);
        ID_VARDEC (idn) = IDS_VARDEC (_ids);
        ID_AVIS (idn) = IDS_AVIS (_ids);

        /* create new N_Ncode node  */
        nassign = MakeAssign (MakeLet (coden, _ids), NULL);
        /* set correct backref to defining assignment */
        AVIS_SSAASSIGN (IDS_AVIS (_ids)) = nassign;
        coden = MakeNCode (MakeBlock (nassign, NULL), idn);

        /* create surrounding cuboids */
        wln = CutSlices (array_null, array_shape, NWITH_BOUND1 (wln), NWITH_BOUND2 (wln),
                         gen_shape, wln, coden);

        /* the original part can still be found at first position in wln.
           Now create grids. */
        if (NWITH_STEP (wln))
            wln = CompleteGrid (NWITH_BOUND1 (wln), NWITH_BOUND2 (wln), NWITH_STEP (wln),
                                NWITH_WIDTH (wln), gen_shape, wln, coden, arg_info);

        /* if new codes have been created, add them to code list */
        if (NPART_NEXT (NWITH_PART (wln))) {
            NCODE_NEXT (coden) = NWITH_CODE (wln);
            NWITH_CODE (wln) = coden;
        }

        /* free the above made arrays */
        array_null = FreeTree (array_null);
    }
    array_shape = FreeTree (array_shape);

    DBUG_RETURN (wln);
}

/** <!--********************************************************************-->
 *
 * @fn node *CreateEmptyGenWLReplacement( node *wl, node *arg_info)
 *
 *   @brief  computes the replacement for the given WL under the assumption that
 *           the generator is empty, i.e.,
 *
 *           with( lb <= iv < ub)              =>     with( 0*shp <= iv <shp)
 *           genarray( shp, exp, dexp)                genarray( shp, dexp, ---)
 *
 *           with( lb <= iv < ub)              =>     a
 *           modarray( a, NULL, exp)
 *
 *           with( lb <= iv < ub)              =>     neutral
 *           fold( fun, neutral, exp)
 *
 *           NOTE HERE, that wl is either MODIFIED in place or FREED entirely!!
 *
 *   @param  node *wl       :  N_with
 *           node *arg_info :  N_INFO
 *   @return node *         :  modified N_with
 ******************************************************************************/
static node *
CreateEmptyGenWLReplacement (node *wl, node *arg_info)
{
    ids *let_ids;
    int dim, i;
    node *lb, *ub, *lbe, *ube, *vardec;
    node *code;
    node *tmpn, *assignn, *idn, *blockn;
    ids *_ids;
    char *varname;
    types *type;

    node *res;

    DBUG_ENTER ("CreateEmptyGenWLReplacement");

    switch (NWITH_TYPE (wl)) {
    case WO_genarray:
        res = wl;
        /*
         * First, we change the generator to full scope.
         */
        let_ids = LET_IDS (INFO_WLPG_LET (arg_info));
        dim = GetDim (IDS_TYPE (let_ids));
        lb = NWITH_BOUND1 (wl);
        ub = NWITH_BOUND2 (wl);
        lbe = ARRAY_AELEMS (lb);
        ube = ARRAY_AELEMS (ub);

        i = 0;
        while ((i < dim) && (lbe != NULL)) {
            NUM_VAL (EXPRS_EXPR (lbe)) = 0;
            NUM_VAL (EXPRS_EXPR (ube)) = IDS_SHAPE (let_ids, i);

            lbe = EXPRS_NEXT (lbe);
            ube = EXPRS_NEXT (ube);
            i++;
        }

        if (NWITH_STEP (wl)) {
            NWITH_STEP (wl) = FreeTree (NWITH_STEP (wl));
        }
        if (NWITH_WIDTH (wl)) {
            NWITH_WIDTH (wl) = FreeTree (NWITH_WIDTH (wl));
        }

        /*
         * Now we have to change the code. Either we can use DEFAULT (easy)
         * or we have to create zeros (ugly).
         */
        code = NWITH_CODE (wl);
        if (NWITH_DEFAULT (wl) != NULL) {
            NCODE_CBLOCK (code) = FreeTree (NCODE_CBLOCK (code));
            NCODE_CBLOCK (code) = MakeEmpty ();

            NCODE_CEXPR (code) = FreeTree (NCODE_CEXPR (code));
            NCODE_CEXPR (code) = DupTree (NWITH_DEFAULT (wl));

        } else {
            blockn = NCODE_CBLOCK (code);
            tmpn = BLOCK_INSTR (blockn);

            if (N_empty == NODE_TYPE (tmpn)) {
                /* there is no instruction in the block right now. */
                BLOCK_INSTR (blockn) = FreeTree (BLOCK_INSTR (blockn));
                /* first, introduce a new variable */
                varname = TmpVar ();
                _ids = MakeIds (varname, NULL, ST_regular);
                /* determine type of expr in the operator (result of body) */
                type = ID_TYPE (NWITH_CEXPR (INFO_WLPG_WL (arg_info)));
                vardec = MakeVardec (StringCopy (varname), DupOneTypes (type), NULL);
                IDS_VARDEC (_ids) = vardec;
                IDS_AVIS (_ids) = VARDEC_AVIS (vardec);
                INFO_WLPG_FUNDEF (arg_info)
                  = AddVardecs (INFO_WLPG_FUNDEF (arg_info), vardec);

                tmpn = CreateZeroFromType (type, FALSE, INFO_WLPG_FUNDEF (arg_info));

                /* replace N_empty with new assignment "_ids = [0,..,0]" */
                assignn = MakeAssign (MakeLet (tmpn, _ids), NULL);
                BLOCK_INSTR (blockn) = assignn;

                /* set correct backref to defining assignment */
                AVIS_SSAASSIGN (IDS_AVIS (_ids)) = assignn;

                /* replace CEXPR */
                idn = MakeId (StringCopy (varname), NULL, ST_regular);
                ID_VARDEC (idn) = IDS_VARDEC (_ids);
                ID_AVIS (idn) = IDS_AVIS (_ids);
                tmpn = NWITH_CODE (INFO_WLPG_WL (arg_info));
                NCODE_CEXPR (tmpn) = FreeTree (NCODE_CEXPR (tmpn));
                NCODE_CEXPR (tmpn) = idn;

            } else {
                /* we have a non-empty block.
                   search last assignment and make it the only one in the block. */
                while (ASSIGN_NEXT (tmpn)) {
                    tmpn = ASSIGN_NEXT (tmpn);
                }
                assignn = DupTree (tmpn);
                FreeTree (BLOCK_INSTR (blockn));
                FreeTree (LET_EXPR (ASSIGN_INSTR (assignn)));
                BLOCK_INSTR (blockn) = assignn;
                _ids = LET_IDS (ASSIGN_INSTR (assignn));
                type = IDS_TYPE (_ids);

                tmpn = CreateZeroFromType (type, FALSE, INFO_WLPG_FUNDEF (arg_info));
                NCODE_FLAG (NWITH_CODE (INFO_WLPG_WL (arg_info))) = TRUE;

                LET_EXPR (ASSIGN_INSTR (assignn)) = tmpn;
            }
        }
        break;
    case WO_modarray:
        res = DupTree (NWITH_ARRAY (wl));
        wl = FreeTree (wl);
        break;
    default:
        res = DupTree (NWITH_NEUTRAL (wl));
        wl = FreeTree (wl);
        break;
    }

    DBUG_RETURN (res);
}

/** <!--********************************************************************-->
 *
 * @fn node *CreateNewAssigns( node *expr, node *f_def)
 *
 *   @brief expects (expr) to point to an identifier and generates as many
 *          new assigns as the value of the shapevektor at position 0 of (expr)
 *          indicates.
 *
 *   @param  node *expr  :  expr
 *           node *f_def :  N_fundef
 *   @return node *      :  a chained list of N_assign nodes
 ******************************************************************************/
static node *
CreateNewAssigns (node *expr, node *f_def)
{
    int i;
    node *tmp1, *tmp2, *tmp3, *nassigns, *vardec;
    ids *_ids;
    char *nvarname;

    DBUG_ENTER ("CreateNewAssigns");

    DBUG_ASSERT ((expr != NULL), "Expr is empty");
    DBUG_ASSERT ((NODE_TYPE (expr) == N_id), "CreateNewAssigns not called with N_id");
    DBUG_ASSERT ((ID_DIM (expr) == 1), "Dimension of Id is not 1");
    DBUG_ASSERT ((ID_SHPSEG (expr) != NULL), "SHPSEG of Id points to NULL");

    nassigns = NULL;

    for (i = ID_SHAPE (expr, 0) - 1; i >= 0; i--) {
        nvarname = TmpVarName (ID_NAME (expr));
        _ids = MakeIds (nvarname, NULL, ST_regular);
        vardec = MakeVardec (StringCopy (nvarname), DupOneTypes (ID_TYPE (expr)), NULL);
        IDS_VARDEC (_ids) = vardec;
        IDS_AVIS (_ids) = VARDEC_AVIS (vardec);

        f_def = AddVardecs (f_def, vardec);

        /* index position for selection */
        tmp1 = MakeNum (i);
        /* the array for selection */
        tmp2 = MakeExprs (DupTree (expr), NULL);

        tmp3 = MakePrf (F_idx_sel, MakeExprs (tmp1, tmp2));

        nassigns = MakeAssign (MakeLet (tmp3, _ids), nassigns);

        /* set correct backref to defining assignment */
        AVIS_SSAASSIGN (IDS_AVIS (_ids)) = nassigns;
    }

    DBUG_RETURN (nassigns);
}

/** <!--********************************************************************-->
 *
 * @fn gen_shape_t PropagateArrayConstants( node **expr)
 *
 *   @brief expects (*expr) to point either to a scalar constant, to an array,
 *          or to an identifyer.
 *          If (**expr) is constant or structural constant, the according node
 *          (N_array / scalar) is freshly generated and (*expr) is modified to
 *          point to the new node. The old one is freed!
 *          If (**expr) is an identifier, the node is checked if it is possible
 *          to create an structural constant.
 *          It returns GV_constant iff (**expr) is constant or
 *          (*expr) == NULL!!
 *
 *   @param  node **expr  :  expr
 *   @return gen_shape_t  :  GV_constant, GV_struct_constant, GV_known_shape,
 *                           GV_unknown_shape
 ******************************************************************************/

static gen_shape_t
PropagateArrayConstants (node **expr)
{
    constant *const_expr;
    struct_constant *sco_expr;
    node *tmp;
    gen_shape_t gshape;

    DBUG_ENTER ("PropagateArrayConstants");

    gshape = GV_unknown_shape;

    if ((*expr) != NULL) {
        const_expr = COAST2Constant ((*expr));
        if (const_expr != NULL) {
            gshape = GV_constant;
            (*expr) = FreeTree (*expr);
            (*expr) = COConstant2AST (const_expr);
            const_expr = COFreeConstant (const_expr);

        } else {
            sco_expr = SCOExpr2StructConstant ((*expr));
            if (sco_expr != NULL) {
                gshape = GV_struct_constant;
                /*
                 * as the sco_expr may share some subexpressions with (*expr),
                 * we have to duplicate these BEFORE deleting (*expr)!!!
                 */
                tmp = SCODupStructConstant2Expr (sco_expr);
                (*expr) = FreeTree (*expr);
                (*expr) = tmp;
                sco_expr = SCOFreeStructConstant (sco_expr);

            } else if (ID_DIM ((*expr)) == 1) {
                if (ID_SHPSEG ((*expr)) != NULL) {
                    if (ID_SHAPE ((*expr), 0) > 0) {
                        gshape = GV_known_shape;
                    }
                }
            }
        }

    } else {
        gshape = GV_constant;
    }

    DBUG_RETURN (gshape);
}

/** <!--********************************************************************-->
 *
 * @fn gen_prop_t CheckGeneratorBounds( node *wl, shape *max_shp)
 *
 *   @brief expects the bound expression for lb and ub to be constants!
 *          checks, whether these fit into the shape given by max_shp.
 *          If they exceed max_shp, they are "fitted"!
 *          Furthermore, it is checked whether the generator is empty
 *          (GPT_empty is returned) or may cover the entire range
 *          (GPT_full is returned). Otherwise GPT_partial is returned.
 *
 *   @param  node *wl        :  N_Nwith
 *           shape *max_shape:  shape of the wl
 *   @return gen_prob_t      :  GPT_empty, GPT_full, GPT_partial or GPT_unknown
 ******************************************************************************/

static gen_prop_t
CheckGeneratorBounds (node *wl, shape *max_shp)
{
    node *lbe, *ube;
    int dim;
    int lbnum, ubnum, tnum;
    gen_prop_t res;

    DBUG_ENTER ("CheckGeneratorBounds");

    lbe = ARRAY_AELEMS (NWITH_BOUND1 (wl));
    ube = ARRAY_AELEMS (NWITH_BOUND2 (wl));
    res = GPT_full;

    dim = 0;
    while (lbe) {
        DBUG_ASSERT ((ube != NULL), "dimensionality differs in lower and upper bound!");
        DBUG_ASSERT (((NODE_TYPE (EXPRS_EXPR (lbe)) == N_num)
                      && (NODE_TYPE (EXPRS_EXPR (ube)) == N_num)),
                     "generator bounds must be constant!");
        lbnum = NUM_VAL (EXPRS_EXPR (lbe));
        ubnum = NUM_VAL (EXPRS_EXPR (ube));

        if ((NWITH_TYPE (wl) == WO_modarray) || (NWITH_TYPE (wl) == WO_genarray)) {
            DBUG_ASSERT ((dim < SHGetDim (max_shp)),
                         "dimensionality of lb greater than that of the result!");
            tnum = SHGetExtent (max_shp, dim);
            if (lbnum < 0) {
                lbnum = NUM_VAL (EXPRS_EXPR (lbe)) = 0;
                WARN (NODE_LINE (wl),
                      ("lower bound of WL-generator in dim %d below zero: set to 0",
                       dim));
            } else if (lbnum > 0) {
                res = GPT_partial;
            }
            if (ubnum > tnum) {
                ubnum = NUM_VAL (EXPRS_EXPR (ube)) = tnum;
                WARN (NODE_LINE (wl),
                      ("upper bound of WL-generator in dim %d greater than shape:"
                       " set to %d",
                       dim, tnum));
            } else if (ubnum < tnum) {
                res = GPT_partial;
            }
        }

        if (lbnum >= ubnum) {
            /* empty set of indices */
            res = GPT_empty;
            break;
        }

        dim++;
        lbe = EXPRS_NEXT (lbe);
        ube = EXPRS_NEXT (ube);
    }
    DBUG_RETURN (res);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGmodul(node *arg_node, node *arg_info)
 *
 *   @brief traverses function definitions only!
 *
 *   @param  node *arg_node:  N_modul
 *           node *arg_info:  N_info
 *   @return node *        :  N_modul
 ******************************************************************************/

node *
WLPGmodul (node *arg_node, node *arg_info)
{
    DBUG_ENTER ("WLPGmodul");

    INFO_WLPG_MODUL (arg_info) = arg_node;

    if (MODUL_FUNS (arg_node) != NULL) {
        MODUL_FUNS (arg_node) = Trav (MODUL_FUNS (arg_node), arg_info);
    }

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGfundef(node *arg_node, node *arg_info)
 *
 *   @brief resets INFO components WL and FUNDEF, apply Constant Folding if
 *          we are in phase PH_wlpartgen and starts the traversal of the given
 *          fundef
 *
 *   @param  node *arg_node:  N_fundef
 *           node *arg_info:  N_info
 *   @return node *        :  N_fundef
 ******************************************************************************/

node *
WLPGfundef (node *arg_node, node *arg_info)
{
    DBUG_ENTER ("WLPGfundef");

    INFO_WLPG_WL (arg_info) = NULL;
    INFO_WLPG_FUNDEF (arg_info) = arg_node;

    if (compiler_phase == PH_wlpartgen) {
        /*
         * to compute primitive function for constant expressions, especially
         * for bounds, steps and widths of WL's generator.
         */
        if (optimize & OPT_CF) {
            arg_node
              = SSAConstantFolding (arg_node, INFO_WLPG_MODUL (arg_info)); /* ssacf_tab */
        }

        if ((break_after == PH_wlpartgen) && (0 == strcmp (break_specifier, "cf"))) {
            if (FUNDEF_NEXT (arg_node) != NULL) {
                FUNDEF_NEXT (arg_node) = Trav (FUNDEF_NEXT (arg_node), arg_info);
            }
        } else {
            if (FUNDEF_BODY (arg_node)) {
                FUNDEF_INSTR (arg_node) = Trav (FUNDEF_INSTR (arg_node), arg_info);
            }

            if (FUNDEF_NEXT (arg_node) != NULL) {
                FUNDEF_NEXT (arg_node) = Trav (FUNDEF_NEXT (arg_node), arg_info);
            }
        }
    } else {
        /* compiler_phase == PH_sacopt */
        if (FUNDEF_BODY (arg_node)) {
            FUNDEF_INSTR (arg_node) = Trav (FUNDEF_INSTR (arg_node), arg_info);
        }

        if (FUNDEF_NEXT (arg_node) != NULL) {
            FUNDEF_NEXT (arg_node) = Trav (FUNDEF_NEXT (arg_node), arg_info);
        }
    }

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGassign(node *arg_node, node *arg_info)
 *
 *   @brief traverse instruction. If this creates new assignments in
 *          INFO_WLPG_NASSIGNS these are inserted in front of the actual one.
 *
 *   @param  node *arg_node:  N_assign
 *           node *arg_info:  N_info
 *   @return node *        :  N_assign
 ******************************************************************************/

node *
WLPGassign (node *arg_node, node *arg_info)
{
    node *iterator;

    DBUG_ENTER ("WLPGassign");

    ASSIGN_INSTR (arg_node) = Trav (ASSIGN_INSTR (arg_node), arg_info);

    iterator = NULL;

    if (INFO_WLPG_NASSIGNS (arg_info) != NULL) {
        iterator = INFO_WLPG_NASSIGNS (arg_info);
        while (ASSIGN_NEXT (iterator)) {
            iterator = ASSIGN_NEXT (iterator);
        }
        ASSIGN_NEXT (iterator) = arg_node;
        /* to traverse not in circle */
        iterator = ASSIGN_NEXT (iterator);

        arg_node = INFO_WLPG_NASSIGNS (arg_info);
        INFO_WLPG_NASSIGNS (arg_info) = NULL;

        if (ASSIGN_NEXT (iterator) != NULL) {
            ASSIGN_NEXT (iterator) = Trav (ASSIGN_NEXT (iterator), arg_info);
        }
    } else {
        if (ASSIGN_NEXT (arg_node) != NULL) {
            ASSIGN_NEXT (arg_node) = Trav (ASSIGN_NEXT (arg_node), arg_info);
        }
    }

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGlet(node *arg_node, node *arg_info)
 *
 *   @brief traverses in expression and checks assigned ids for constant
 *          value and sets corresponding AVIS_SSACONST attribute
 *
 *   @param  node *arg_node:  N_let
 *           node *arg_info:  N_info
 *   @return node *        :  N_let
 ******************************************************************************/
node *
WLPGlet (node *arg_node, node *arg_info)
{

    DBUG_ENTER ("WLPGlet");

    DBUG_ASSERT ((LET_EXPR (arg_node) != NULL), "N_let with empty EXPR attribute.");

    INFO_WLPG_LET (arg_info) = arg_node;

    /*
     * Only ids nodes with one entry are considered.
     * Tuple of constants are not provided/supported in SaC until now.
     */
    if ((LET_IDS (arg_node) != NULL) && (IDS_NEXT (LET_IDS (arg_node)) == NULL)) {

        if (AVIS_SSACONST (IDS_AVIS (LET_IDS (arg_node))) == NULL) {
            AVIS_SSACONST (IDS_AVIS (LET_IDS (arg_node)))
              = COAST2Constant (LET_EXPR (arg_node));
        }
    }

    LET_EXPR (arg_node) = Trav (LET_EXPR (arg_node), arg_info);

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGNwith(node *arg_node, node *arg_info)
 *
 *   @brief  start traversal of this WL and store information in new arg_info
 *           node. The only N_Npart node (inclusive body) is traversed.
 *           Afterwards, if certain conditions are fulfilled,
 *           the WL is transformed into a WL with generators describing a full
 *           partition.
 *
 *   @param  node *arg_node:  N_Nwith
 *           node *arg_info:  N_info
 *   @return node *        :  N_Nwith
 ******************************************************************************/

node *
WLPGNwith (node *arg_node, node *arg_info)
{
    node *let_tmp;
    bool replace_wl = FALSE;

    DBUG_ENTER ("WLPGNwith");

    /*
     * Information about last N_let has to be stacked before traversal
     */
    let_tmp = INFO_WLPG_LET (arg_info);

    /*
     * The CODEs have to be traversed as they may contain further (nested) WLs
     * and I want to modify bottom up.
     */
    if (NWITH_CODE (arg_node) != NULL) {
        NWITH_CODE (arg_node) = Trav (NWITH_CODE (arg_node), arg_info);
    }

    /* Pop N_let */
    INFO_WLPG_LET (arg_info) = let_tmp;

    /*
     * Once a full partition has been created, we do not need to inspect
     * the generators anymore. The indicator for this is the PARTS attribute.
     * Initially, it is set to -1; if we have successfully generated a full
     * partition, it carries a positive value.
     */
    if (NWITH_PARTS (arg_node) == -1) {

        /*
         * initialize WL traversal
         */
        INFO_WLPG_WL (arg_info) = arg_node; /* store the current node for later */

        /*
         * traverse the one and only (!) PART.
         * Besides minor changes in the generator, two values are computed
         * during this traversal:
         *
         *  INFO_WLPG_GENVAR(arg_info) and INFO_WLPG_GENPROP(arg_info) !!
         */
        DBUG_ASSERT ((NWITH_PART (arg_node) != NULL),
                     "NWITH_PARTS is -1 although no PART is available!");
        DBUG_ASSERT ((NPART_NEXT (NWITH_PART (arg_node)) == NULL),
                     "NWITH_PARTS is -1 although more than one PART is available!");
        NWITH_PART (arg_node) = Trav (NWITH_PART (arg_node), arg_info);

        /*
         * Now, we traverse the WITHOP sons for propagating (structural) constants.
         */
        NWITH_WITHOP (arg_node) = Trav (NWITH_WITHOP (arg_node), arg_info);

        if (INFO_WLPG_GENPROP (arg_info) == GPT_empty) {
            arg_node = CreateEmptyGenWLReplacement (arg_node, arg_info);
            replace_wl = TRUE;

        } else if (INFO_WLPG_GENPROP (arg_info) == GPT_full) {
            NWITH_PARTS (arg_node) = 1;

            if (NWITH_TYPE (arg_node) == WO_genarray) {
                if (NWITH_DEFAULT (arg_node) != NULL) {
                    NWITH_DEFAULT (arg_node) = FreeTree (NWITH_DEFAULT (arg_node));
                }
            }

        } else if ((INFO_WLPG_GENPROP (arg_info) == GPT_partial)
                   && ((INFO_WLPG_GENSHP (arg_info) == GV_constant)
                       || (INFO_WLPG_GENSHP (arg_info) == GV_struct_constant))) {
            arg_node = CreateFullPartition (arg_node, arg_info);
        }

    } else {
        /*
         * traverse the WITHOP sons for propagating (structural) constants.
         */
        NWITH_WITHOP (arg_node) = Trav (NWITH_WITHOP (arg_node), arg_info);
    }

    INFO_WLPG_WL (arg_info) = NULL;
    INFO_WLPG_LET (arg_info) = NULL;

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGNwithop( node *arg_node, node *arg_info)
 *
 *   @brief Substitutes NWITHOP_SHAPE into the N_Nwithop node.
 *
 *   @param  node *arg_node:  N_Nwithop
 *           node *arg_info:  N_info
 *   @return node *        :  N_Nwithop
 ******************************************************************************/

node *
WLPGNwithop (node *arg_node, node *arg_info)
{
    node *nassigns, *f_def;
    gen_shape_t current_shape;

    DBUG_ENTER ("WLPGNwithop");

    f_def = INFO_WLPG_FUNDEF (arg_info);

    switch (NWITHOP_TYPE (arg_node)) {
    case WO_genarray:
        if (NWITHOP_SHAPE (arg_node) != NULL) {
            NWITHOP_SHAPE (arg_node) = Trav (NWITHOP_SHAPE (arg_node), arg_info);
        }
        current_shape = PropagateArrayConstants (&(NWITHOP_SHAPE (arg_node)));
        if (current_shape == GV_known_shape) {
            nassigns = CreateNewAssigns (NWITHOP_SHAPE (arg_node), f_def);
            NWITHOP_SHAPE (arg_node)
              = CreateStructConstant (NWITHOP_SHAPE (arg_node), nassigns);
            current_shape = GV_struct_constant;
            INFO_WLPG_NASSIGNS (arg_info)
              = AppendAssigns (nassigns, INFO_WLPG_NASSIGNS (arg_info));
        }

        if (INFO_WLPG_GENSHP (arg_info) < current_shape) {
            INFO_WLPG_GENSHP (arg_info) = current_shape;
        }
        break;

    case WO_modarray:
        if (NWITHOP_ARRAY (arg_node) != NULL) {
            NWITHOP_ARRAY (arg_node) = Trav (NWITHOP_ARRAY (arg_node), arg_info);
        }
        break;

    case WO_foldfun:
        /* here is no break missing */
    case WO_foldprf:
        if (NWITHOP_NEUTRAL (arg_node) != NULL) {
            NWITHOP_NEUTRAL (arg_node) = Trav (NWITHOP_NEUTRAL (arg_node), arg_info);
        }
        break;

    default:
        DBUG_ASSERT ((0), "illegal NWITHOP_TYPE found!");
        break;
    }

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGNpart(node *arg_node, node *arg_info)
 *
 *   @brief traverse only generator to propagate arrays
 *
 *   @param  node *arg_node:  N_Npart
 *           node *arg_info:  N_info
 *   @return node *        :  N_Npart
 ******************************************************************************/

node *
WLPGNpart (node *arg_node, node *arg_info)
{
    DBUG_ENTER ("WLPGNpart");

    NPART_GEN (arg_node) = Trav (NPART_GEN (arg_node), arg_info);

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPGNgenerator(node *arg_node, node *arg_info)
 *
 *   @brief  bounds, step and width vectors are substituted into the generator.
 *           Generators that surmount the array bounds (like [-5,3] or
 *           [11,10] > [maxdim1,maxdim2] = [10,10]) are changed to fitting
 *           gens.
 *           Via INFO_WLPG_GENPROP( arg_info) the status of the generator is
 *           returned. Possible values are (poss. ambiguities are resolved top
 *           to bottom):
 *           GPT_empty   : the generator is empty!
 *           GPT_full    : the generator covers the entire range!
 *           GPT_partial : the generator has constant upper and lower bounds,
 *                         but  - most likely  - only a part is covered!
 *           GPT_unknown : we don't know anything !
 *
 *           Via INFO_WLPG_GENSHP( arg_info) the status of the bounds, step and
 *           width vectors is returned.
 *           Possible values are (poss. ambiguities are resolved top
 *           to bottom):
 *           GV_constant        : the vectors are constant!
 *           GV_struct_constant : the vektors are at least structural constants!
 *           GV_unknown_shape   : we don't know anything !
 *
 *   @param  node *arg_node:  N_Ngenerator
 *           node *arg_info:  N_info
 *   @return node *        :  N_Ngenerator
 ******************************************************************************/

node *
WLPGNgenerator (node *arg_node, node *arg_info)
{
    node *wln, *f_def, *nassigns, *step, *width;
    ids *let_ids;
    shape *shp;
    bool check_bounds, check_stepwidth;
    gen_prop_t gprop;
    gen_shape_t current_shape, gshape;

    DBUG_ENTER ("WLPGNgenerator");

    wln = INFO_WLPG_WL (arg_info);
    f_def = INFO_WLPG_FUNDEF (arg_info);

    /*
     * First, we try to propagate (structural) constants into all sons:
     */
    current_shape = PropagateArrayConstants (&(NGEN_BOUND1 (arg_node)));
    if (current_shape == GV_known_shape) {
        nassigns = CreateNewAssigns (NGEN_BOUND1 (arg_node), f_def);
        NGEN_BOUND1 (arg_node) = CreateStructConstant (NGEN_BOUND1 (arg_node), nassigns);
        gshape = GV_struct_constant;
        INFO_WLPG_NASSIGNS (arg_info)
          = AppendAssigns (nassigns, INFO_WLPG_NASSIGNS (arg_info));
    } else {
        gshape = current_shape;
    }

    current_shape = PropagateArrayConstants (&(NGEN_BOUND2 (arg_node)));
    if (current_shape == GV_known_shape) {
        nassigns = CreateNewAssigns (NGEN_BOUND2 (arg_node), f_def);
        NGEN_BOUND2 (arg_node) = CreateStructConstant (NGEN_BOUND2 (arg_node), nassigns);
        current_shape = GV_struct_constant;
        INFO_WLPG_NASSIGNS (arg_info)
          = AppendAssigns (nassigns, INFO_WLPG_NASSIGNS (arg_info));
    }
    if (gshape < current_shape) {
        gshape = current_shape;
    }
    check_bounds = (gshape == GV_constant);

    current_shape = PropagateArrayConstants (&(NGEN_STEP (arg_node)));
    if (current_shape == GV_known_shape) {
        nassigns = CreateNewAssigns (NGEN_STEP (arg_node), f_def);
        NGEN_STEP (arg_node) = CreateStructConstant (NGEN_STEP (arg_node), nassigns);
        current_shape = GV_struct_constant;
        INFO_WLPG_NASSIGNS (arg_info)
          = AppendAssigns (nassigns, INFO_WLPG_NASSIGNS (arg_info));
    }
    if (gshape < current_shape) {
        gshape = current_shape;
    }

    check_stepwidth = (current_shape <= GV_struct_constant);

    current_shape = PropagateArrayConstants (&(NGEN_WIDTH (arg_node)));
    if (current_shape == GV_known_shape) {
        nassigns = CreateNewAssigns (NGEN_WIDTH (arg_node), f_def);
        NGEN_WIDTH (arg_node) = CreateStructConstant (NGEN_WIDTH (arg_node), nassigns);
        current_shape = GV_struct_constant;
        INFO_WLPG_NASSIGNS (arg_info)
          = AppendAssigns (nassigns, INFO_WLPG_NASSIGNS (arg_info));
    }
    if (gshape < current_shape) {
        gshape = current_shape;
    }

    check_stepwidth = (check_stepwidth && (current_shape <= GV_struct_constant));

    /*
     * check bound ranges
     */
    let_ids = LET_IDS (INFO_WLPG_LET (arg_info));
    if (check_bounds && (GetShapeDim (IDS_TYPE (let_ids)) >= 0)) {
        shp = SHOldTypes2Shape (IDS_TYPE (let_ids));
        gprop = CheckGeneratorBounds (wln, shp);
        shp = SHFreeShape (shp);
        if ((gprop == GPT_full) && (NGEN_STEP (arg_node) != NULL)) {
            gprop = GPT_partial;
        }
    } else if (gshape == GV_struct_constant) {
        gprop = GPT_partial;
    } else {
        gprop = GPT_unknown;
    }

    if (check_stepwidth) {
        /* normalize step and width */
        switch (NormalizeStepWidth (&NGEN_STEP (arg_node), &NGEN_WIDTH (arg_node))) {
        case 1:
            ABORT (NODE_LINE (wln), ("component of width greater than step"));
        case 2:
            ABORT (NODE_LINE (wln), ("component of width less 0"));
        case 3:
            ABORT (NODE_LINE (wln), ("width vector without step vector"));
        }
    }

    step = NGEN_STEP (arg_node);
    width = NGEN_WIDTH (arg_node);

    INFO_WLPG_GENPROP (arg_info) = gprop;
    INFO_WLPG_GENSHP (arg_info) = gshape;

    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPartitionGeneration( node *arg_node)
 *
 *   @brief  Starting point for the partition generation if it was called
 *           from main. First transform code in SSA form.
 *           Then start the traverse of the AST and after that convert back
 *           to standard form.
 *
 *   @param  node *arg_node:  the whole syntax tree
 *   @return node *        :  the transformed syntax tree
 ******************************************************************************/

node *
WLPartitionGeneration (node *arg_node)
{
    funtab *tmp_tab;
    node *arg_info;

    DBUG_ENTER ("WLPartitionGeneration");

    DBUG_ASSERT ((NODE_TYPE (arg_node) == N_modul),
                 "WLPartitionGeneration not started with modul node");

    DBUG_PRINT ("WLPG", ("starting WLPartitionGeneration"));

    /* transformation in ssa-form */
    arg_node = DoSSA (arg_node);
    /* necessary to guarantee, that the compilation can be stopped
       during the call of DoSSA */
    if ((break_after == PH_wlpartgen)
        && ((0 == strcmp (break_specifier, "l2f"))
            || (0 == strcmp (break_specifier, "cha"))
            || (0 == strcmp (break_specifier, "ssa")))) {
        goto DONE;
    }

    arg_info = MakeInfo ();

    tmp_tab = act_tab;
    act_tab = wlpg_tab;

    arg_node = Trav (arg_node, arg_info);

    arg_info = FreeTree (arg_info);
    act_tab = tmp_tab;

    /* undo tranformation in ssa-form */
    arg_node = UndoSSA (arg_node);
    /* necessary to guarantee, that the compilation can be stopped
       during the call of UndoSSA */
    if ((break_after == PH_wlpartgen)
        && ((0 == strcmp (break_specifier, "ussa"))
            || (0 == strcmp (break_specifier, "f2l")))) {
        goto DONE;
    }

DONE:
    DBUG_RETURN (arg_node);
}

/** <!--********************************************************************-->
 *
 * @fn node *WLPartitionGenerationOPT( node *arg_node)
 *
 *   @brief  Starting point for the partition generation if it was called
 *           from optimize.
 *
 *   @param  node *arg_node:  the whole syntax tree
 *   @return node *        :  the transformed syntax tree
 ******************************************************************************/

node *
WLPartitionGenerationOPT (node *arg_node)
{
    funtab *tmp_tab;
    node *arg_info;

    DBUG_ENTER ("WLPartitionGenerationOPT");

    DBUG_ASSERT ((NODE_TYPE (arg_node) == N_fundef),
                 "WLPartitionGenerationOPT not started with fundef node");

    DBUG_PRINT ("WLPG", ("starting WLPartitionGenerationOPT"));

    arg_info = MakeInfo ();

    tmp_tab = act_tab;
    act_tab = wlpg_tab;

    arg_node = Trav (arg_node, arg_info);

    arg_info = FreeTree (arg_info);
    act_tab = tmp_tab;

    DBUG_RETURN (arg_node);
}
