/*
 *
 * $Log$
 * Revision 1.1  2000/01/03 17:33:17  cg
 * Initial revision
 *
 *
 */

/*
 * Revision 1.3  1999/09/17 14:33:34  cg
 * New version of SAC heap manager:
 *  - no special API functions for top arena.
 *  - coalascing is always done deferred.
 *  - no doubly linked free lists any more.
 *
 * Revision 1.2  1999/07/16 09:41:16  cg
 * Added facilities for heap management diagnostics.
 *
 * Revision 1.1  1999/07/08 12:28:56  cg
 * Initial revision
 *
 *
 */

/*****************************************************************************
 *
 * file:   memalign.c
 *
 * prefix: none
 *
 * description:
 *
 *   This file provides SAC heap manager specific implementations of the
 *   functions memalign() and valloc(); these guarantee the allocation of
 *   memory chunks with particular alignments.
 *
 *   Although programs generated by sac2c will never use these functions,
 *   they are nevertheless mandatory because functions from external module
 *   or class implementation might rely on them.
 *
 *****************************************************************************/

#include "heapmgr.h"

#include <unistd.h>

/******************************************************************************
 *
 * function:
 *   void *memalign(size_byte_t alignment, size_byte_t size)
 *
 * description:
 *
 *   SAC heap manager specific implementation of memalign().
 *
 ******************************************************************************/

void *
memalign (size_byte_t alignment, size_byte_t size)
{
    void *mem;
    size_byte_t misalign, size_needed;
    SAC_HM_header_t *freep, *prefixp;
    SAC_HM_arena_t *arena;
    size_unit_t offset_units;

    DIAG_INC_LOCK (SAC_HM_call_memalign);

    if (alignment <= UNIT_SIZE) {
        /* automatic alignment */
        return (malloc (size));
    }

    /* worst case allocation for a posteriori alignment */
    size_needed
      = SAC_MAX (size + alignment + (UNIT_SIZE + UNIT_SIZE), ARENA_5_MINCS * UNIT_SIZE);

    DIAG_DEC_LOCK (SAC_HM_call_malloc);
    mem = malloc (size_needed);

    misalign = ((unsigned long int)mem) % alignment;

    if (misalign == 0) {
        /* Memory is already correctly aligned. */
        return (mem);
    }

    offset_units = (alignment - misalign) / UNIT_SIZE;

    if (offset_units < 2) {
        /*
         * Offset is too small to host administration info for free prefix.
         */
        offset_units += alignment / UNIT_SIZE;
    }

    prefixp = ((SAC_HM_header_t *)mem) - 2;
    arena = SAC_HM_LARGECHUNK_ARENA (prefixp);
    freep = prefixp + offset_units;

    /*
     * Setup memory location to be returned.
     */

    SAC_HM_LARGECHUNK_SIZE (freep) = SAC_HM_LARGECHUNK_SIZE (prefixp) - offset_units;
    SAC_HM_LARGECHUNK_ARENA (freep) = arena;
    SAC_HM_LARGECHUNK_PREVSIZE (freep) = offset_units;

    /*
     * Setup memory location returned by malloc();
     * this will now be de-allocated again using free().
     */

    SAC_HM_LARGECHUNK_SIZE (prefixp) = offset_units;

    DIAG_DEC_LOCK (SAC_HM_call_free);
    free (prefixp + 2);

    return ((void *)(freep + 2));
}

/******************************************************************************
 *
 * function:
 *   void *valloc(size_byte_t size)
 *
 * description:
 *
 *   SAC heap manager specific implementation of valloc().
 *
 *
 *
 ******************************************************************************/

void *
valloc (size_byte_t size)
{
    DIAG_INC_LOCK (SAC_HM_call_valloc);
    DIAG_DEC_LOCK (SAC_HM_call_memalign);

    return (memalign (getpagesize (), size));
}
