/*
 *
 * $Log$
 * Revision 2.1  1999/02/23 12:42:58  sacbase
 * new release made
 *
 * Revision 1.3  1998/04/13 19:59:14  dkr
 * added ConstSegs
 *
 * Revision 1.2  1998/04/13 18:11:20  dkr
 * rcs-header added
 *
 *
 *
 */

/*
 * fun_name  fun_string
 *
 */

WLP (All, "All")
WLP (Cubes, "Cubes")
WLP (ConstSegs, "ConstSegs")
WLP (NoBlocking, "NoBlocking")
WLP (Bv, "Bv")
WLP (BvL0, "BvL0")
WLP (BvL1, "BvL1")
WLP (BvL2, "BvL2")
WLP (Ubv, "Ubv")
