#!/bin/bash

# Run one test to ensure correct results.

rm -f $1.exe $1.exe.c 

source UnitTestRunGrep1.config

logfile="logWorks"$( sac2c -V | grep rev | cut -f 4 -d\ )
echo $( sac2c -V) >> $logfile
echo $( date)       >> $logfile

echo Starting Worktest: sac2c -v0 -target seq -O3 $1 -o $1.exe $optson  >> $logfile
sac2c -v0 -target seq -O3 $1 -o $1.exe $optson   | tee -a $logfile
	./$1.exe                     >>       $logfile
	z=$?
	if [ 0 -eq $z ]; then 
          echo Worktest: $1 OK  | tee -a $logfile
          junk=0
	else 
           echo -e '\a\a'            
           echo Worktest: $1 failed with completion code $z  | tee -a $logfile
	fi
rm -f $1.exe $1.exe.c
