#!/bin/bash

# Run all unit tests, and check results.

logfile="logGreps"$( sac2c-p -V | grep rev | cut -f 4 -d\ )
rm -f $logfile

for i in *.sac;
do
  UnitTestRunGrep1 $i
done;
 rm -f grepn* grepd*
 cp $logfile logGreps

