#!/bin/bash

# Run one test to ensure correct results.

rm -f $1.exe $1.exe.c 

source UnitTestRunGrep1.config

# HUSH echo Starting Worktest: sac2c -v0 -O3 $1 -o $1.exe $optson
sac2c -v0 -O3 $1 -o $1.exe $optson
	./$1.exe
	z=$?
	if [ 0 -eq $z ]; then 
          # HUSH echo Worktest: $1 OK; 
          junk=0
	else 
           echo -e '\a\a'
           echo Worktest: $1 failed with completion code $z; 
	fi
rm -f $1.exe $1.exe.c
