#ifndef BACKENDtype
#define BACKENDtype(type)
#endif

#ifndef BACKENDstring
#define BACKENDstring(string)
#endif

#ifndef BACKEND
#define BACKEND(type, string) BACKENDtype (type) BACKENDstring (string)
#endif

BACKEND (BE_mutc, "MUTC")
BACKEND (BE_c99, "C99")
BACKEND (BE_cuda, "CUDA")
BACKEND (BE_cudahybrid, "CudaHybrid")
BACKEND (BE_omp, "omp")
BACKEND (BE_distmem, "DistMem")

#undef BACKENDtype
#undef BACKENDstring
#undef BACKEND
