/*
 *
 * $Id$
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dbug.h"

#include "globals.h"

#include "icm2c_std.h"
#include "icm2c_prf.h"
#include "icm2c_wl.h"
#include "icm2c_mt.h"
#include "icm2c_sched.h"
#include "icm2c_error.h"

/*
 * Variables needed for the code generated by "icm_betest.c":
 */
node *arg_info = NULL;

#define ICM_ALL
#include "icm_vars.c"
#undef ICM_ALL

/******************************************************************************
 *
 * Function:
 *   int main( int argc, char *argv[])
 *
 * Description:
 *   main function
 *
 ******************************************************************************/

int
main (int argc, char *argv[])
{
    char buffer[1024];
    int scanf_res;
    char c;

    DBUG_ENTER ("main");

    /*
     * preset some globals used for the compilation of ICM's
     */
    GLOBinitializeGlobal ();
    global.outfile = stdout;
    global.print_objdef_for_header_file = 0;
    global.indent = 0;

    printf ("#include \"../runtime/sac.h\"\n");
    scanf_res = scanf ("%s", buffer);
    while (scanf_res > 0) {
        if (buffer[strlen (buffer) - 1] == '(') {
            buffer[strlen (buffer) - 1] = '\0';
        }

        DBUG_PRINT ("BEtest", ("icm found: %s\n", buffer));

#define ICM_ALL
#include "icm_betest.c"
#undef ICM_ALL
        if (0 == strcmp (buffer, "clear-indent")) {
            global.indent = 0;
        } else {
            printf ("icm %s not defined!\n", buffer);

            /*
             * Now, we have to consume the rest of the line.
             */
            do {
                c = getchar ();
            } while (c != '\n');
            ungetc ((int)c, stdin);
        }

        scanf ("%s\n", buffer);
        scanf_res = scanf ("%s", buffer);
    }

    DBUG_RETURN (0);
}
