/*
 *
 * $Log$
 * Revision 3.8  2004/11/24 19:30:44  jhb
 * compile
 *
 * Revision 3.7  2004/11/24 15:59:10  jhb
 * removed include my_dbug NameTuples.h
 *
 * Revision 3.6  2003/09/20 14:18:53  dkr
 * icm2c_prf.h added
 *
 * Revision 3.5  2002/09/09 14:18:01  dkr
 * icm2c_error.h added
 *
 * Revision 3.4  2002/06/02 21:40:09  dkr
 * include of NameTuples.h added
 *
 * Revision 3.3  2001/05/11 14:36:56  cg
 * Include of new header file icm2c_sched.h added
 *
 * Revision 3.2  2001/03/22 19:16:44  dkr
 * include of tree.h eliminated
 *
 * Revision 3.1  2000/11/20 18:01:14  sacbase
 * new release made
 *
 * Revision 2.1  1999/02/23 12:42:36  sacbase
 * new release made
 *
 * Revision 1.57  1998/05/13 07:15:43  cg
 * added include of icm2c_mt.h
 *
 * Revision 1.56  1998/05/04 16:01:39  dkr
 * added includes: icm2c_std.h, icm2c_wl.h
 *
 * Revision 1.55  1998/05/03 13:09:17  dkr
 * added icm2c_wl.h
 *
 * Revision 1.54  1998/04/25 16:25:20  sbs
 *  new icm2c / BEtest mechanism implemented!
 *
 */

#include "types.h"
#include "tree_basic.h"
#include "tree_compound.h"
#include "globals.h"
#include "convert.h"
#include "icm2c_std.h"
#include "icm2c_prf.h"
#include "icm2c_wl.h"
#include "icm2c_mt.h"
#include "icm2c_sched.h"
#include "icm2c_error.h"
#include "icm2c_cuda.h"
#include "icm2c_rtspec.h"
#include "icm2c_fp.h"
#include "icm2c_ia.h"

/*
 * Variables needed for the code generated by "icm_icm2c.c":
 *
 * The choice to make them static rather than local to the Print-funktions
 * is motivated by the fact, that this decision spares one "traversal" through
 * icm.data and thus allows us to use ICM_ALL instead of specific includes
 * for each ICM!
 */

#define ICM_ALL
#include "icm_vars.c"
#undef ICM_ALL

/*
 * Now, we can create ALL Print-functions by a single include!!!
 * The respective external declarations are produced locally in print.c!!
 */

#define ICM_ALL
#include "icm_icm2c.c"
#undef ICM_ALL
